'use strict';
(function(root){
  const LARGE_CATALOG_THRESHOLD=600,MAX_QUERY_PRODUCTS=320,MAX_QUERY_SHARDS=32;
  const normalizeSearch=value=>String(value||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^\p{L}\p{N}.]+/gu,' ').trim();
  const tokensFor=query=>normalizeSearch(query).split(/\s+/).filter(token=>token.length>1);
  const allShardIds=manifest=>Object.keys(manifest?.shards||{}).sort((a,b)=>Number(a)-Number(b));
  function rowScore(row,tokens){const name=normalizeSearch(row?.n),brand=normalizeSearch(row?.b),category=normalizeSearch(row?.c),q=normalizeSearch(row?.q);let score=0,matched=0;for(const token of tokens){let hit=0;if(name.includes(token))hit=12;else if(category.includes(token))hit=8;else if(brand.includes(token))hit=5;else if(q.includes(token))hit=1;if(hit){matched++;score+=hit;}}if(tokens.length&&matched===tokens.length)score+=12;return score;}
  function selectShardIds(manifest,index,query,detectedFamily,category=''){
    const all=allShardIds(manifest),rows=Array.isArray(index)?index:[],exact=String(category||'').trim();
    if(exact){const ids=[];for(const row of rows){if(String(row?.c||'')!==exact)continue;const id=String(row?.s??'');if(id&&manifest.shards?.[id]&&!ids.includes(id))ids.push(id);}return ids;}
    const tokens=tokensFor(query);if(Number(manifest?.itemCount||0)<=LARGE_CATALOG_THRESHOLD||!tokens.length)return all;
    const ranked=rows.map(row=>({row,score:rowScore(row,tokens)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||String(a.row?.i||'').localeCompare(String(b.row?.i||''))).slice(0,MAX_QUERY_PRODUCTS);
    if(!ranked.length)return all;const ids=[];for(const {row} of ranked){const id=String(row?.s??'');if(id&&manifest.shards?.[id]&&!ids.includes(id))ids.push(id);if(ids.length>=MAX_QUERY_SHARDS)break;}return ids.length?ids:all;
  }
  if(typeof module!=='undefined'&&module.exports)module.exports={LARGE_CATALOG_THRESHOLD,MAX_QUERY_PRODUCTS,MAX_QUERY_SHARDS,normalizeSearch,selectShardIds,rowScore};
  if(!root||typeof root.fetch!=='function')return;
  const nativeFetch=root.fetch.bind(root);let manifestPromise=null,indexPromise=null,homePromise=null;const shardPromises=new Map(),queryPromises=new Map();
  const fetchJson=async url=>{const response=await nativeFetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`Catalog request failed: ${url} (${response.status})`);return response.json();};
  const numeric=value=>value!==null&&value!==undefined&&value!==''&&Number.isFinite(Number(value))?Number(value):null;
  function adaptCanonical(product){if(!product||!product.id||!product.name)return null;if(Number.isFinite(Number(product.price)))return {...product,price:Number(product.price)};const offer=product.bestOffer||{},price=numeric(offer.price)??numeric(product.priceFrom);if(price===null)return null;const total=numeric(offer.totalPrice)??numeric(product.totalPriceFrom),shipping=numeric(offer.shippingCost)??(total!==null?Math.max(0,total-price):null);return {id:String(product.id),name:String(product.name),description:String(product.description||''),brand:String(product.brand||''),category:String(product.category||''),image:String(product.image||product.imageUrl||offer.imageUrl||''),price,shippingCost:shipping,currency:String(offer.currency||product.currency||'EUR'),inStock:String(offer.availability||'').toUpperCase()==='IN_STOCK',merchantCount:numeric(product.offerCount),active:true,testData:true,affiliateUrl:String(offer.affiliateUrl||''),catalogCanonical:true};}
  function flattenShard(payload){const values=Array.isArray(payload)?payload:(payload&&typeof payload==='object'?Object.values(payload):[]);return values.map(adaptCanonical).filter(Boolean);}
  function initialParams(){try{const p=new URL(root.location?.href||'https://fundblick.de/').searchParams;return {query:p.get('q')||'',category:p.get('category')||''};}catch{return {query:'',category:''};}}
  function onSearchPage(){try{return /\/search\.html$/i.test(root.location?.pathname||'')||!!root.document?.querySelector?.('.results-page');}catch{return false;}}
  async function manifestOnly(){if(!manifestPromise)manifestPromise=(async()=>{const manifest=await fetchJson('catalog/manifest.json');if(!manifest||!manifest.searchFile||!manifest.shards)throw new Error('Invalid live catalog manifest');root.FundBlickCatalog={...(root.FundBlickCatalog||{}),manifest,largeCatalog:Number(manifest.itemCount||0)>LARGE_CATALOG_THRESHOLD,load,loadHome,manifestOnly,meta,selectShardIds};return manifest;})();return manifestPromise;}
  async function meta(){const manifest=await manifestOnly();if(!indexPromise)indexPromise=fetchJson('catalog/'+manifest.searchFile);const index=await indexPromise;root.FundBlickCatalog={...(root.FundBlickCatalog||{}),manifest,index,largeCatalog:Number(manifest.itemCount||0)>LARGE_CATALOG_THRESHOLD,load,loadHome,manifestOnly,meta,selectShardIds};return {manifest,index};}
  async function loadShard(id,entry){const key=String(id);if(!shardPromises.has(key))shardPromises.set(key,fetchJson('catalog/'+entry.file).then(flattenShard));return shardPromises.get(key);}
  async function loadAll(manifest){const ids=allShardIds(manifest),payloads=await Promise.all(ids.map(id=>loadShard(id,manifest.shards[id]))),byId=new Map();payloads.flat().forEach(p=>byId.set(p.id,{...(byId.get(p.id)||{}),...p}));return [...byId.values()];}
  async function loadHome(){if(!homePromise)homePromise=(async()=>{const manifest=await manifestOnly();if(!manifest.homeDealFile)return loadAll(manifest);const products=flattenShard(await fetchJson('catalog/'+manifest.homeDealFile));root.FundBlickCatalog={...(root.FundBlickCatalog||{}),homeProducts:products,load,loadHome,manifestOnly,meta,selectShardIds};return products;})();return homePromise;}
  async function load(query=initialParams().query,category=initialParams().category){if(!normalizeSearch(query)&&!category&&!onSearchPage())return loadHome();const key=`${normalizeSearch(query)}|${category||'__all__'}`;if(!queryPromises.has(key))queryPromises.set(key,(async()=>{const {manifest,index}=await meta(),ids=selectShardIds(manifest,index,query,null,category),payloads=await Promise.all(ids.map(id=>loadShard(id,manifest.shards[id]))),byId=new Map();payloads.flat().forEach(p=>{if(category&&p.category!==category)return;byId.set(p.id,{...(byId.get(p.id)||{}),...p});});const products=[...byId.values()];root.FundBlickCatalog={...(root.FundBlickCatalog||{}),manifest,index,products,loadedShardIds:ids,partial:ids.length<allShardIds(manifest).length,activeCategory:category||'',largeCatalog:Number(manifest.itemCount||0)>LARGE_CATALOG_THRESHOLD,load,loadHome,manifestOnly,meta,selectShardIds};return products;})());return queryPromises.get(key);}
  const jsonResponse=async data=>new Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
  root.fetch=async function(input,init){const raw=typeof input==='string'?input:(input&&input.url)||'';let url=null,path='';try{url=new URL(raw,root.location?.href||'https://fundblick.de/');path=url.pathname;}catch{}if(raw==='catalog-live'||path.endsWith('/catalog-live')){const p=initialParams();return jsonResponse(await load(url?.searchParams.get('q')||p.query,url?.searchParams.get('category')||p.category));}if(path.endsWith('/products.json'))return jsonResponse([]);return nativeFetch(input,init);};
  root.FundBlickCatalog={load,loadHome,manifestOnly,meta,selectShardIds,largeCatalog:false};
})(typeof window!=='undefined'?window:null);
