'use strict';
(function(root){
  const labels={
    de:{'home.living':'Wohnen & Haushalt','home.furniture':'Möbel','home.lighting':'Lampen & Beleuchtung','home.decor':'Dekoration','pet.equestrian':'Pferd & Reitsport','pet.dog':'Hund','health.supplements':'Gesundheit & Nahrungsergänzung','home.garden.robot-mowers':'Mähroboter','home.garden.robot-mower-accessories':'Mähroboter-Zubehör','gifts.personalized.keychains':'Personalisierte Schlüsselanhänger','gifts.personalized.jewelry':'Personalisierter Schmuck','gifts.personalized.photo-gifts':'Personalisierte Fotogeschenke','craft.jewelry-making.supplies':'Schmuckzubehör & Bastelmaterial'},
    en:{'home.living':'Home & Living','home.furniture':'Furniture','home.lighting':'Lighting','home.decor':'Decoration','pet.equestrian':'Horses & Equestrian','pet.dog':'Dogs','health.supplements':'Health & Supplements','home.garden.robot-mowers':'Robot lawn mowers','home.garden.robot-mower-accessories':'Robot mower accessories','gifts.personalized.keychains':'Personalized keychains','gifts.personalized.jewelry':'Personalized jewelry','gifts.personalized.photo-gifts':'Personalized photo gifts','craft.jewelry-making.supplies':'Jewelry making supplies'},
    tr:{'home.living':'Ev & Yaşam','home.furniture':'Mobilya','home.lighting':'Aydınlatma','home.decor':'Dekorasyon','pet.equestrian':'At & Binicilik','pet.dog':'Köpek','health.supplements':'Sağlık & Takviyeler','home.garden.robot-mowers':'Robot çim biçme makineleri','home.garden.robot-mower-accessories':'Robot çim biçme makinesi aksesuarları','gifts.personalized.keychains':'Kişiye özel anahtarlıklar','gifts.personalized.jewelry':'Kişiye özel takılar','gifts.personalized.photo-gifts':'Kişiye özel fotoğraf hediyeleri','craft.jewelry-making.supplies':'Takı yapım malzemeleri'},
    ru:{'home.living':'Дом и быт','home.furniture':'Мебель','home.lighting':'Освещение','home.decor':'Декор','pet.equestrian':'Лошади и конный спорт','pet.dog':'Собаки','health.supplements':'Здоровье и пищевые добавки','home.garden.robot-mowers':'Роботы-газонокосилки','home.garden.robot-mower-accessories':'Аксессуары для роботов-газонокосилок','gifts.personalized.keychains':'Персонализированные брелоки','gifts.personalized.jewelry':'Персонализированные украшения','gifts.personalized.photo-gifts':'Персонализированные фотоподарки','craft.jewelry-making.supplies':'Материалы для изготовления украшений'},
    ar:{'home.living':'المنزل والمعيشة','home.furniture':'أثاث','home.lighting':'إضاءة','home.decor':'ديكور','pet.equestrian':'الخيل والفروسية','pet.dog':'الكلاب','health.supplements':'الصحة والمكملات','home.garden.robot-mowers':'جزازات العشب الروبوتية','home.garden.robot-mower-accessories':'ملحقات جزازات العشب الروبوتية','gifts.personalized.keychains':'سلاسل مفاتيح مخصصة','gifts.personalized.jewelry':'مجوهرات مخصصة','gifts.personalized.photo-gifts':'هدايا صور مخصصة','craft.jewelry-making.supplies':'مستلزمات صناعة المجوهرات'},
    pl:{'home.living':'Dom i wnętrze','home.furniture':'Meble','home.lighting':'Oświetlenie','home.decor':'Dekoracje','pet.equestrian':'Konie i jeździectwo','pet.dog':'Psy','health.supplements':'Zdrowie i suplementy','home.garden.robot-mowers':'Roboty koszące','home.garden.robot-mower-accessories':'Akcesoria do robotów koszących','gifts.personalized.keychains':'Personalizowane breloki','gifts.personalized.jewelry':'Personalizowana biżuteria','gifts.personalized.photo-gifts':'Personalizowane fotoprezenty','craft.jewelry-making.supplies':'Materiały do tworzenia biżuterii'},
    ro:{'home.living':'Casă & Locuință','home.furniture':'Mobilier','home.lighting':'Iluminat','home.decor':'Decorațiuni','pet.equestrian':'Cai & Echitație','pet.dog':'Câini','health.supplements':'Sănătate & Suplimente','home.garden.robot-mowers':'Roboți de tuns iarba','home.garden.robot-mower-accessories':'Accesorii pentru roboți de tuns iarba','gifts.personalized.keychains':'Brelocuri personalizate','gifts.personalized.jewelry':'Bijuterii personalizate','gifts.personalized.photo-gifts':'Cadouri foto personalizate','craft.jewelry-making.supplies':'Materiale pentru bijuterii'},
    uk:{'home.living':'Дім і побут','home.furniture':'Меблі','home.lighting':'Освітлення','home.decor':'Декор','pet.equestrian':'Коні та кінний спорт','pet.dog':'Собаки','health.supplements':'Здоров’я та добавки','home.garden.robot-mowers':'Роботи-газонокосарки','home.garden.robot-mower-accessories':'Аксесуари для роботів-газонокосарок','gifts.personalized.keychains':'Персоналізовані брелоки','gifts.personalized.jewelry':'Персоналізовані прикраси','gifts.personalized.photo-gifts':'Персоналізовані фотоподарунки','craft.jewelry-making.supplies':'Матеріали для виготовлення прикрас'},
    it:{'home.living':'Casa & Abitare','home.furniture':'Mobili','home.lighting':'Illuminazione','home.decor':'Decorazione','pet.equestrian':'Cavalli & Equitazione','pet.dog':'Cani','health.supplements':'Salute & Integratori','home.garden.robot-mowers':'Robot tagliaerba','home.garden.robot-mower-accessories':'Accessori per robot tagliaerba','gifts.personalized.keychains':'Portachiavi personalizzati','gifts.personalized.jewelry':'Gioielli personalizzati','gifts.personalized.photo-gifts':'Regali fotografici personalizzati','craft.jewelry-making.supplies':'Materiali per creare gioielli'},
    fr:{'home.living':'Maison & Habitat','home.furniture':'Meubles','home.lighting':'Éclairage','home.decor':'Décoration','pet.equestrian':'Chevaux & Équitation','pet.dog':'Chiens','health.supplements':'Santé & Compléments','home.garden.robot-mowers':'Robots tondeuses','home.garden.robot-mower-accessories':'Accessoires pour robots tondeuses','gifts.personalized.keychains':'Porte-clés personnalisés','gifts.personalized.jewelry':'Bijoux personnalisés','gifts.personalized.photo-gifts':'Cadeaux photo personnalisés','craft.jewelry-making.supplies':'Fournitures pour bijoux'},
    es:{'home.living':'Hogar','home.furniture':'Muebles','home.lighting':'Iluminación','home.decor':'Decoración','pet.equestrian':'Caballos & Equitación','pet.dog':'Perros','health.supplements':'Salud & Suplementos','home.garden.robot-mowers':'Robots cortacésped','home.garden.robot-mower-accessories':'Accesorios para robots cortacésped','gifts.personalized.keychains':'Llaveros personalizados','gifts.personalized.jewelry':'Joyas personalizadas','gifts.personalized.photo-gifts':'Regalos fotográficos personalizados','craft.jewelry-making.supplies':'Materiales para hacer joyas'},
    pt:{'home.living':'Casa','home.furniture':'Móveis','home.lighting':'Iluminação','home.decor':'Decoração','pet.equestrian':'Cavalos & Equitação','pet.dog':'Cães','health.supplements':'Saúde & Suplementos','home.garden.robot-mowers':'Robôs corta-relva','home.garden.robot-mower-accessories':'Acessórios para robôs corta-relva','gifts.personalized.keychains':'Porta-chaves personalizados','gifts.personalized.jewelry':'Joias personalizadas','gifts.personalized.photo-gifts':'Presentes fotográficos personalizados','craft.jewelry-making.supplies':'Materiais para fazer joias'}
  };
  function getLabel(category,language='de'){return labels[language]?.[category]||labels.en[category]||'';}
  const api={getLabel};
  if(typeof module==='object'&&module.exports)module.exports=api;
  if(root)root.FundBlickCategoryLabels=api;
})(typeof window!=='undefined'?window:null);
