'use strict';
const FB_LANG=window.FundBlickLanguage?.lang||'de';
const LABELS={de:{type:'Produkttyp',material:'Material',style:'Stil',room:'Einsatzbereich',price:'Produktpreis',brand:'Hersteller / Marke',merchant:'Händler'},en:{type:'Product type',material:'Material',style:'Style',room:'Use / room',price:'Product price',brand:'Brand',merchant:'Merchant'},ru:{type:'Тип товара',material:'Материал',style:'Стиль',room:'Область применения',price:'Цена товара',brand:'Производитель / бренд',merchant:'Магазин'}};
const L=(key,fallback)=>(LABELS[FB_LANG]||LABELS.en)[key]||fallback;
window.FB_CATEGORY_SCHEMAS={
 furniture:{label:'Möbel',icon:'🪑',terms:['home.furniture','möbel','moebel','hocker','mosaiktisch','beistelltisch','bistrotisch','couchtisch','gartentisch','esstisch','tisch','stuhl','bank','sessel','sofa','kommode','schrank','regal'],facets:[{key:'type',label:L('type','Produkttyp'),type:'multi',values:['Hocker','Mosaiktisch','Beistelltisch','Bistrotisch','Couchtisch','Esstisch / Gartentisch','Stuhl','Bank','Sessel / Sofa','Kommode / Schrank','Regal']},{key:'material',label:L('material','Material'),type:'multi',values:['Holz','Metall','Mosaik','Keramik','Rattan','Textil','Leder']},{key:'style',label:L('style','Stil'),type:'multi',values:['Orientalisch','Marokkanisch','Mediterran','Vintage','Modern','Industrial']}]},
 lighting:{label:'Lampen & Beleuchtung',icon:'💡',terms:['home.lighting','lampen','beleuchtung','lampe','leuchte','laterne','windlicht','teelichthalter'],facets:[{key:'type',label:L('type','Produkttyp'),type:'multi',values:['Hänge- / Pendelleuchte','Wandlampe','Deckenleuchte','Steh- / Tischlampe','Laterne','Windlicht','Teelichthalter']},{key:'material',label:L('material','Material'),type:'multi',values:['Metall','Messing','Glas','Eisen','Kupfer','Holz']},{key:'style',label:L('style','Stil'),type:'multi',values:['Orientalisch','Marokkanisch','Mediterran','Vintage','Modern','Industrial']}]},
 decor:{label:'Dekoration',icon:'🏺',terms:['home.decor','dekoration','deko','vase','figur','spiegel','kissen','schale','tablett','wanddekoration'],facets:[{key:'type',label:L('type','Produkttyp'),type:'multi',values:['Vase','Figur','Spiegel','Kissen','Schale / Tablett','Wanddekoration']},{key:'material',label:L('material','Material'),type:'multi',values:['Metall','Holz','Glas','Keramik','Textil','Stein']},{key:'style',label:L('style','Stil'),type:'multi',values:['Orientalisch','Marokkanisch','Mediterran','Vintage','Modern','Industrial']}]},
 living:{label:'Wohnen & Haushalt',icon:'🏠',terms:['home.living','wohnen','haushalt','korb','waschbecken','brunnen','aufbewahrung'],facets:[{key:'type',label:L('type','Produkttyp'),type:'multi',values:['Korb / Aufbewahrung','Waschbecken','Brunnen','Wohnaccessoire']},{key:'material',label:L('material','Material'),type:'multi',values:['Metall','Holz','Keramik','Stein','Textil','Naturfaser','Glas']},{key:'room',label:L('room','Einsatzbereich'),type:'multi',values:['Wohnbereich','Bad','Garten / Außenbereich']}]}
};
/* Only expose attributes that can be supported by real feed text/data. */
window.FB_COMMON_FACETS=[{key:'price',label:L('price','Produktpreis'),type:'price'},{key:'brand',label:L('brand','Hersteller / Marke'),type:'brand'},{key:'merchants',label:L('merchant','Händler'),type:'merchant'}];
window.FB_detectCategory=function(query){const q=String(query||'').toLocaleLowerCase('de');let best=null,bestLen=0;for(const [key,s] of Object.entries(window.FB_CATEGORY_SCHEMAS)){for(const term of s.terms){if(q.includes(term)&&term.length>bestLen){best={key,...s};bestLen=term.length}}}return best;};
window.FB_facetVisible=function(facet,state,query){if(!facet.when)return true;const w=facet.when;if(w.queryIncludes&&!w.queryIncludes.some(x=>String(query).toLowerCase().includes(x)))return false;const vals=state?.[w.facet]||[];if(w.equals&&!vals.includes(w.equals))return false;if(w.not&&vals.includes(w.not))return false;return true;};
