'use strict';
const FB_LANG=window.FundBlickLanguage?.lang||'de';
const LABELS={de:{type:'Produkttyp',material:'Material',style:'Stil',room:'Einsatzbereich',price:'Produktpreis',brand:'Hersteller / Marke',merchant:'Händler',area:'Rasenfläche',connectivity:'Mobilfunk',condition:'Zustand',model:'Modell'},en:{type:'Product type',material:'Material',style:'Style',room:'Use / room',price:'Product price',brand:'Brand',merchant:'Merchant',area:'Lawn area',connectivity:'Mobile connectivity',condition:'Condition',model:'Model'},ru:{type:'Тип товара',material:'Материал',style:'Стиль',room:'Область применения',price:'Цена товара',brand:'Производитель / бренд',merchant:'Магазин',area:'Площадь газона',connectivity:'Мобильная связь',condition:'Состояние',model:'Модель'}};
const L=(key,fallback)=>(LABELS[FB_LANG]||LABELS.en)[key]||fallback;
window.FB_CATEGORY_SCHEMAS={
 'electronics.cameras.trail-cameras':{label:window.FundBlickCategoryLabels?.getLabel('electronics.cameras.trail-cameras',FB_LANG)||'Wildkameras',icon:'📷',terms:['electronics.cameras.trail-cameras','wildkamera','wildkameras','fotofalle','fotofallen','jagdkamera','trail camera'],facets:[{key:'productType',label:L('type','Produkttyp'),type:'multi',values:['Wildkamera']}]},
 'electronics.cameras.trail-camera-accessories':{label:'Wildkamera-Zubehör',icon:'🔋',terms:['electronics.cameras.trail-camera-accessories','wildkamera-zubehör','wildkamera zubehör','solarpanel für wildkameras','kamerahalterung','trail camera accessories'],facets:[{key:'productType',label:L('type','Produkttyp'),type:'multi',values:['Solarpanel für Wildkameras','Kamerahalterung']}]},
 furniture:{label:'Möbel',icon:'🪑',terms:['home.furniture','möbel','moebel','hocker','mosaiktisch','beistelltisch','bistrotisch','couchtisch','gartentisch','esstisch','tisch','stuhl','bank','sessel','sofa','kommode','schrank','regal'],facets:[{key:'type',label:L('type','Produkttyp'),type:'multi',values:['Hocker','Mosaiktisch','Beistelltisch','Bistrotisch','Couchtisch','Esstisch / Gartentisch','Stuhl','Bank','Sessel / Sofa','Kommode / Schrank','Regal']},{key:'material',label:L('material','Material'),type:'multi',values:['Holz','Metall','Mosaik','Keramik','Rattan','Textil','Leder']},{key:'style',label:L('style','Stil'),type:'multi',values:['Orientalisch','Marokkanisch','Mediterran','Vintage','Modern','Industrial']}]},
 lighting:{label:'Lampen & Beleuchtung',icon:'💡',terms:['home.lighting','lampen','beleuchtung','lampe','leuchte','laterne','windlicht','teelichthalter','tischlampe','tischleuchte','lichterkette','batterien','fernbedienung'],facets:[{key:'room',label:L('room','Einsatzbereich'),type:'multi',values:['Garten / Außenbereich','Wohnbereich']},{key:'type',label:L('type','Produkttyp'),type:'multi',values:['Hänge- / Pendelleuchte','Wandlampe','Deckenleuchte','Steh- / Tischlampe','Laterne','Windlicht','Teelichthalter','Lampenfassung / Anschluss','Lichterkette','Batterien','Fernbedienung']},{key:'material',label:L('material','Material'),type:'multi',values:['Metall','Messing','Glas','Eisen','Kupfer','Holz']},{key:'style',label:L('style','Stil'),type:'multi',values:['Orientalisch','Marokkanisch','Mediterran','Vintage','Modern','Industrial']}]},
 decor:{label:'Dekoration',icon:'🏺',terms:['home.decor','dekoration','deko','vase','figur','spiegel','kissen','schale','tablett','wanddekoration','kerze','kerzen','led-kerze','led kerze','blockkerzen','stabkerzen','teelicht','dekolicht','schwimmleuchten','schwimmlicht'],facets:[{key:'room',label:L('room','Einsatzbereich'),type:'multi',values:['Garten / Außenbereich','Wohnbereich']},{key:'type',label:L('type','Produkttyp'),type:'multi',values:['Vase / Blumentopf','Figur','Spiegel','Kissen / Sitzkissen','Schale / Tablett','Wanddekoration','Kerze / Kerzenhalter','LED-Kerze','LED-Dekolicht']},{key:'material',label:L('material','Material'),type:'multi',values:['Metall','Holz','Glas','Keramik','Textil','Stein']},{key:'style',label:L('style','Stil'),type:'multi',values:['Orientalisch','Marokkanisch','Mediterran','Vintage','Modern','Industrial']}]},
 living:{label:'Wohnen & Haushalt',icon:'🏠',terms:['home.living','wohnen','haushalt','korb','waschbecken','brunnen','aufbewahrung'],facets:[{key:'type',label:L('type','Produkttyp'),type:'multi',values:['Korb / Aufbewahrung','Waschbecken','Brunnen','Wohnaccessoire']},{key:'material',label:L('material','Material'),type:'multi',values:['Metall','Holz','Keramik','Stein','Textil','Naturfaser','Glas']},{key:'room',label:L('room','Einsatzbereich'),type:'multi',values:['Wohnbereich','Bad','Garten / Außenbereich']}]},
 equestrian:{label:'Pferd & Reitsport',icon:'🐴',terms:['pet.equestrian','pferd','pferde','reitsport','equestrian','zusatzfutter','horse care'],facets:[{key:'type',label:L('type','Produkttyp'),type:'multi',values:['Ergänzungsfutter','Pferdepflege','Bundle']}]},
 'robot-mowers':{label:'Mähroboter',icon:'🌱',terms:['home.garden.robot-mowers','mähroboter','maehroboter','rasenroboter','robotic mower','robot mower','anthbot genie','anthbot pion'],facets:[{key:'lawnAreaM2',label:L('area','Rasenfläche'),type:'threshold',values:[500,1000,1500,2000,3000,5000],unit:'m²'},{key:'connectivity4G',label:L('connectivity','Mobilfunk'),type:'multi',values:['4G']},{key:'condition',label:L('condition','Zustand'),type:'multi',values:['Neu','Generalüberholt']},{key:'model',label:L('model','Modell'),type:'multi'}]},
 'gifts.personalized.keychains':{label:'Personalisierte Schlüsselanhänger',icon:'🔑',terms:['gifts.personalized.keychains','personalisierter schlüsselanhänger','foto schlüsselanhänger','foto schluesselanhaenger','schlüsselanhänger','schluesselanhaenger'],facets:[{key:'productType',label:L('type','Produkttyp'),type:'multi',values:['Schlüsselanhänger']}]},
 'gifts.personalized.jewelry':{label:'Personalisierter Schmuck',icon:'💎',terms:['gifts.personalized.jewelry','personalisierte schmuckstücke','halskette mit foto','armband personalisiert','personalisierter schmuck','fotokette','projektionskette'],facets:[{key:'productType',label:L('type','Produkttyp'),type:'multi',values:['Schmuck']}]},
 'gifts.personalized.photo-gifts':{label:'Fotogeschenke',icon:'🎁',terms:['gifts.personalized.photo-gifts','personalisiertes fotogeschenk','geschenk mit foto','fotogeschenk','fotogeschenke'],facets:[{key:'productType',label:L('type','Produkttyp'),type:'multi',values:['Fotogeschenk']}]},
 'craft.jewelry-making.supplies':{label:'Schmuckzubehör',icon:'📿',terms:['craft.jewelry-making.supplies','schmuck bastelzubehör','perlenkettenzubehör','perlenkettenzubehoer','schmuckzubehör','schmuckzubehoer'],facets:[{key:'productType',label:L('type','Produkttyp'),type:'multi',values:['Schmuckzubehör']}]},
 'gifts.personalized.other':{label:'Personalisierte Geschenke',icon:'🎁',terms:['gifts.personalized.other','personalisiertes geschenk','personalisierte geschenke'],facets:[{key:'productType',label:L('type','Produkttyp'),type:'multi',values:['Sonstiges personalisiertes Geschenk']}]}
};
/* Only expose attributes that can be supported by real feed text/data. */
window.FB_COMMON_FACETS=[{key:'price',label:L('price','Produktpreis'),type:'price'},{key:'brand',label:L('brand','Hersteller / Marke'),type:'brand'},{key:'merchant',label:L('merchant','Händler'),type:'multi'}];
window.FB_detectCategory=function(query){const q=String(query||'').toLocaleLowerCase('de');let best=null,bestLen=0;for(const [key,s] of Object.entries(window.FB_CATEGORY_SCHEMAS)){for(const term of s.terms){if(q.includes(term)&&term.length>bestLen){best={id:key,key,...s};bestLen=term.length}}}return best;};
window.FB_facetVisible=function(facet,state,query){if(!facet.when)return true;const w=facet.when;if(w.queryIncludes&&!w.queryIncludes.some(x=>String(query).toLowerCase().includes(x)))return false;const vals=state?.[w.facet]||[];if(w.equals&&!vals.includes(w.equals))return false;const vals2=state?.[w.facet]||[];if(w.not&&vals2.includes(w.not))return false;return true;};
