'use strict';
(function(root){
  if(!root||!root.document)return;
  const COPY={
    de:{categories:'Kategorien',deal:'Tagesangebot',dealTitle:'Schnäppchen des Tages',checked:'automatisch geprüft',fundPrice:'FundBlick-Preis',compared:'aktuell verglichen',savingLabel:'Ersparnis zum Vergleichswert',compare:'Angebote vergleichen',noDeal:'Heute kein qualifiziertes Schnäppchen',noDealBody:'FundBlick zeigt lieber keinen künstlichen Deal als einen schwachen Rabatt.',note:'Nur Angebote mit ausreichend belastbaren Vergleichsdaten erscheinen hier.',beta:'Live-Beta · simulierte Testdaten',affiliate:'Bei Händlerlinks können wir eine Vergütung erhalten. Dein Preis ändert sich dadurch nicht.'},
    tr:{categories:'Kategoriler',deal:'Günün fırsatı',dealTitle:'Günün fırsatı',checked:'otomatik kontrol',fundPrice:'FundBlick fiyatı',compared:'güncel karşılaştırma',savingLabel:'Karşılaştırma değerine göre tasarruf',compare:'Teklifleri karşılaştır',noDeal:'Bugün nitelikli fırsat yok',noDealBody:'FundBlick zayıf bir indirimi fırsat gibi göstermemeyi tercih eder.',note:'Yalnızca yeterli karşılaştırma verisine sahip teklifler gösterilir.',beta:'Canlı beta · simüle test verileri',affiliate:'Satıcı bağlantılarından komisyon alabiliriz. Fiyatınız değişmez.'},
    ru:{categories:'Категории',deal:'Предложение дня',dealTitle:'Выгодное предложение дня',checked:'проверяется автоматически',fundPrice:'Цена FundBlick',compared:'актуально сравнено',savingLabel:'Экономия к ориентиру',compare:'Сравнить предложения',noDeal:'Сегодня нет подходящей выгодной сделки',noDealBody:'FundBlick лучше не покажет сделку, чем назовёт слабую скидку выгодной.',note:'Здесь появляются только предложения с достаточными данными для сравнения.',beta:'Live-beta · смоделированные тестовые данные',affiliate:'Мы можем получать вознаграждение по ссылкам продавцов. Ваша цена не меняется.'},
    ar:{categories:'الفئات',deal:'عرض اليوم',dealTitle:'صفقة اليوم',checked:'فحص تلقائي',fundPrice:'سعر FundBlick',compared:'مقارنة حالية',savingLabel:'التوفير مقابل السعر المرجعي',compare:'مقارنة العروض',noDeal:'لا توجد صفقة مؤهلة اليوم',noDealBody:'يفضل FundBlick عدم عرض صفقة على تقديم خصم ضعيف كأنه صفقة.',note:'تظهر هنا فقط العروض التي تتوفر لها بيانات مقارنة موثوقة بما يكفي.',beta:'نسخة تجريبية مباشرة · بيانات اختبار محاكاة',affiliate:'قد نحصل على عمولة من روابط المتاجر دون أن يتغير سعرك.'},
    pl:{categories:'Kategorie',deal:'Oferta dnia',dealTitle:'Okazja dnia',checked:'sprawdzane automatycznie',fundPrice:'Cena FundBlick',compared:'aktualnie porównane',savingLabel:'Oszczędność względem ceny odniesienia',compare:'Porównaj oferty',noDeal:'Dziś brak kwalifikowanej okazji',noDealBody:'FundBlick woli nie pokazać okazji niż udawać słaby rabat.',note:'Pokazujemy tylko oferty z wystarczającymi danymi porównawczymi.',beta:'Live beta · symulowane dane testowe',affiliate:'Możemy otrzymać wynagrodzenie za linki sprzedawców. Twoja cena się nie zmienia.'},
    ro:{categories:'Categorii',deal:'Oferta zilei',dealTitle:'Oferta zilei',checked:'verificată automat',fundPrice:'Preț FundBlick',compared:'comparat acum',savingLabel:'Economie față de referință',compare:'Compară ofertele',noDeal:'Nicio ofertă calificată astăzi',noDealBody:'FundBlick preferă să nu afișeze o ofertă decât să numească un discount slab „ofertă”.',note:'Apar doar ofertele cu suficiente date de comparație.',beta:'Live beta · date de test simulate',affiliate:'Putem primi remunerație pentru linkurile comercianților. Prețul tău nu se schimbă.'},
    uk:{categories:'Категорії',deal:'Пропозиція дня',dealTitle:'Вигідна пропозиція дня',checked:'автоматично перевірено',fundPrice:'Ціна FundBlick',compared:'актуально порівняно',savingLabel:'Економія до орієнтира',compare:'Порівняти пропозиції',noDeal:'Сьогодні немає кваліфікованої вигідної пропозиції',noDealBody:'FundBlick краще не покаже угоду, ніж назве слабку знижку вигідною.',note:'Тут з’являються лише пропозиції з достатніми даними для порівняння.',beta:'Live-beta · змодельовані тестові дані',affiliate:'Ми можемо отримувати винагороду за посилання продавців. Ваша ціна не змінюється.'},
    en:{categories:'Categories',deal:'Deal of the day',dealTitle:'Deal of the day',checked:'checked automatically',fundPrice:'FundBlick price',compared:'currently compared',savingLabel:'Saving vs reference',compare:'Compare offers',noDeal:'No qualified deal today',noDealBody:'FundBlick would rather show no deal than dress up a weak discount.',note:'Only offers with sufficient comparison evidence can appear here.',beta:'Live beta · simulated test data',affiliate:'We may receive compensation from merchant links. Your price does not change.'},
    it:{categories:'Categorie',deal:'Offerta del giorno',dealTitle:'Affare del giorno',checked:'controllato automaticamente',fundPrice:'Prezzo FundBlick',compared:'confrontato ora',savingLabel:'Risparmio sul riferimento',compare:'Confronta offerte',noDeal:'Nessuna offerta qualificata oggi',noDealBody:'FundBlick preferisce non mostrare un affare invece di presentare come tale uno sconto debole.',note:'Compaiono solo offerte con dati comparativi sufficienti.',beta:'Live beta · dati di test simulati',affiliate:'Possiamo ricevere un compenso dai link dei rivenditori. Il tuo prezzo non cambia.'},
    bg:{categories:'Категории',deal:'Оферта на деня',dealTitle:'Сделка на деня',checked:'автоматично проверено',fundPrice:'Цена FundBlick',compared:'сравнено сега',savingLabel:'Спестяване спрямо ориентир',compare:'Сравни офертите',noDeal:'Днес няма квалифицирана оферта',noDealBody:'FundBlick предпочита да няма сделка, вместо слабата отстъпка да се представя като такава.',note:'Показват се само оферти с достатъчно сравнителни данни.',beta:'Live beta · симулирани тестови данни',affiliate:'Може да получим възнаграждение от търговски връзки. Вашата цена не се променя.'},
    hr:{categories:'Kategorije',deal:'Ponuda dana',dealTitle:'Pogodba dana',checked:'automatski provjereno',fundPrice:'FundBlick cijena',compared:'trenutno uspoređeno',savingLabel:'Ušteda prema referenci',compare:'Usporedi ponude',noDeal:'Danas nema kvalificirane ponude',noDealBody:'FundBlick radije neće prikazati pogodbu nego slab popust prikazati kao pogodbu.',note:'Prikazuju se samo ponude s dovoljno podataka za usporedbu.',beta:'Live beta · simulirani testni podaci',affiliate:'Možemo dobiti naknadu putem poveznica trgovaca. Vaša cijena se ne mijenja.'},
    el:{categories:'Κατηγορίες',deal:'Προσφορά ημέρας',dealTitle:'Ευκαιρία της ημέρας',checked:'αυτόματος έλεγχος',fundPrice:'Τιμή FundBlick',compared:'τρέχουσα σύγκριση',savingLabel:'Εξοικονόμηση έναντι αναφοράς',compare:'Σύγκριση προσφορών',noDeal:'Δεν υπάρχει κατάλληλη προσφορά σήμερα',noDealBody:'Το FundBlick προτιμά να μη δείξει προσφορά παρά να παρουσιάσει μια μικρή έκπτωση ως ευκαιρία.',note:'Εμφανίζονται μόνο προσφορές με επαρκή στοιχεία σύγκρισης.',beta:'Live beta · προσομοιωμένα δεδομένα δοκιμής',affiliate:'Μπορεί να λαμβάνουμε αμοιβή από συνδέσμους εμπόρων. Η τιμή σας δεν αλλάζει.'},
    sr:{categories:'Категорије',deal:'Понуда дана',dealTitle:'Погодба дана',checked:'аутоматски проверено',fundPrice:'FundBlick цена',compared:'тренутно упоређено',savingLabel:'Уштеда према референци',compare:'Упореди понуде',noDeal:'Данас нема квалификоване понуде',noDealBody:'FundBlick радије неће приказати погодбу него слаб попуст представити као погодбу.',note:'Приказују се само понуде са довољно података за поређење.',beta:'Live beta · симулирани тест подаци',affiliate:'Можемо добити накнаду преко линкова продаваца. Ваша цена се не мења.'},
    es:{categories:'Categorías',deal:'Oferta del día',dealTitle:'Chollo del día',checked:'comprobado automáticamente',fundPrice:'Precio FundBlick',compared:'comparado ahora',savingLabel:'Ahorro frente a referencia',compare:'Comparar ofertas',noDeal:'Hoy no hay una oferta cualificada',noDealBody:'FundBlick prefiere no mostrar una oferta antes que disfrazar un descuento débil.',note:'Solo aparecen ofertas con suficientes datos comparables.',beta:'Live beta · datos de prueba simulados',affiliate:'Podemos recibir una remuneración por enlaces de comercios. Tu precio no cambia.'},
    fr:{categories:'Catégories',deal:'Offre du jour',dealTitle:'Bon plan du jour',checked:'vérifié automatiquement',fundPrice:'Prix FundBlick',compared:'comparé actuellement',savingLabel:'Économie vs référence',compare:'Comparer les offres',noDeal:'Aucun bon plan qualifié aujourd’hui',noDealBody:'FundBlick préfère ne rien afficher plutôt que de présenter une faible remise comme un bon plan.',note:'Seules les offres avec suffisamment de données comparables apparaissent ici.',beta:'Live beta · données de test simulées',affiliate:'Nous pouvons recevoir une rémunération via les liens marchands. Votre prix ne change pas.'},
    pt:{categories:'Categorias',deal:'Oferta do dia',dealTitle:'Negócio do dia',checked:'verificado automaticamente',fundPrice:'Preço FundBlick',compared:'comparado agora',savingLabel:'Poupança face à referência',compare:'Comparar ofertas',noDeal:'Hoje não há oferta qualificada',noDealBody:'O FundBlick prefere não mostrar uma oferta do que apresentar um desconto fraco como negócio.',note:'Só aparecem ofertas com dados de comparação suficientes.',beta:'Live beta · dados de teste simulados',affiliate:'Podemos receber remuneração através de links de lojas. O seu preço não muda.'},
    fa:{categories:'دسته‌ها',deal:'پیشنهاد روز',dealTitle:'پیشنهاد ویژه روز',checked:'بررسی خودکار',fundPrice:'قیمت FundBlick',compared:'مقایسه فعلی',savingLabel:'صرفه‌جویی نسبت به مرجع',compare:'مقایسه پیشنهادها',noDeal:'امروز پیشنهاد واجد شرایطی وجود ندارد',noDealBody:'FundBlick ترجیح می‌دهد پیشنهادی نشان ندهد تا اینکه تخفیف ضعیفی را پیشنهاد ویژه معرفی کند.',note:'فقط پیشنهادهایی با داده مقایسه کافی نمایش داده می‌شوند.',beta:'نسخه آزمایشی زنده · داده آزمایشی شبیه‌سازی‌شده',affiliate:'ممکن است از لینک فروشندگان کارمزد دریافت کنیم. قیمت شما تغییر نمی‌کند.'},
    sq:{categories:'Kategoritë',deal:'Oferta e ditës',dealTitle:'Oferta e ditës',checked:'kontrolluar automatikisht',fundPrice:'Çmimi FundBlick',compared:'krahasuar tani',savingLabel:'Kursim ndaj referencës',compare:'Krahaso ofertat',noDeal:'Sot nuk ka ofertë të kualifikuar',noDealBody:'FundBlick preferon të mos tregojë ofertë sesa ta quajë një zbritje të dobët ofertë.',note:'Shfaqen vetëm oferta me të dhëna të mjaftueshme krahasimi.',beta:'Live beta · të dhëna testuese të simuluara',affiliate:'Mund të marrim shpërblim nga lidhjet e shitësve. Çmimi juaj nuk ndryshon.'},
    'zh-Hans':{categories:'分类',deal:'今日优惠',dealTitle:'今日好价',checked:'自动检查',fundPrice:'FundBlick 价格',compared:'当前已比较',savingLabel:'相对参考价节省',compare:'比较报价',noDeal:'今天没有符合条件的优惠',noDealBody:'FundBlick 宁可不展示优惠，也不会把很小的折扣包装成好价。',note:'只有具备足够可比较数据的报价才会出现在这里。',beta:'实时测试版 · 模拟测试数据',affiliate:'我们可能通过商家链接获得报酬，但不会改变你的价格。'},
    ku:{categories:'Beş',deal:'Pêşniyara rojê',dealTitle:'Derfeta rojê',checked:'xweber hat kontrolkirin',fundPrice:'Bihayê FundBlick',compared:'niha hat berawirdkirin',savingLabel:'Teserûf li hember referansê',compare:'Pêşniyaran berawird bike',noDeal:'Îro derfetekî guncaw tune ye',noDealBody:'FundBlick tercîh dike ku derfet nede nîşan dan ji ku kêmkirinek lawaz weke derfet nîşan bide.',note:'Tenê pêşniyarên bi daneyên berawirdkirinê yên têr derdikevin.',beta:'Live beta · daneyên testê yên simulekirî',affiliate:'Em dikarin ji lînkên firoşkaran xelat bistînin. Bihayê te naguhere.'}
  };
  const localeMap={de:'de-DE',tr:'tr-TR',ru:'ru-RU',ar:'ar-SA',pl:'pl-PL',ro:'ro-RO',uk:'uk-UA',en:'en-GB',it:'it-IT',bg:'bg-BG',hr:'hr-HR',el:'el-GR',sr:'sr-RS',es:'es-ES',fr:'fr-FR',pt:'pt-PT',fa:'fa-IR',sq:'sq-AL','zh-Hans':'zh-CN',ku:'ku-TR'};
  let products=[];
  const lang=()=>document.querySelector('#language')?.value||document.documentElement.lang||'de';
  const tx=()=>COPY[lang()]||COPY.en;
  const money=value=>new Intl.NumberFormat(localeMap[lang()]||'en-GB',{style:'currency',currency:'EUR'}).format(Number(value));
  const iconFor=category=>/headphone/i.test(category)?'🎧':/television/i.test(category)?'📺':/shoe/i.test(category)?'👟':/smartphone/i.test(category)?'📱':/coffee/i.test(category)?'☕':/heat/i.test(category)?'♨️':'🔎';
  function searchUrl(query){return 'search.html?'+new URLSearchParams({q:query,lang:lang()}).toString();}
  function applyCopy(){const t=tx();document.querySelectorAll('[data-home-key]').forEach(el=>{const value=t[el.dataset.homeKey];if(value)el.textContent=value});document.querySelector('#beta-note')?.replaceChildren(document.createTextNode(t.beta));document.querySelector('#affiliate-note')?.replaceChildren(document.createTextNode(t.affiliate));}
  function renderDeal(){const t=tx(),deal=root.FundBlickDealOfDay?.select(products)||null,content=document.querySelector('#deal-content'),empty=document.querySelector('#deal-empty');if(!content||!empty)return;if(!deal){content.hidden=true;empty.hidden=false;empty.querySelector('strong').textContent=t.noDeal;empty.querySelector('span').textContent=t.noDealBody;return;}empty.hidden=true;content.hidden=false;document.querySelector('#dealBrand').textContent=deal.brand||'FundBlick';document.querySelector('#dealName').textContent=deal.name;document.querySelector('#dealImage').textContent=iconFor(products.find(p=>p.id===deal.productId)?.category||'');document.querySelector('#dealPrice').textContent=money(deal.best.totalPrice);document.querySelector('#dealReference').textContent=money(deal.reference);document.querySelector('#dealDiscount').textContent='−'+Math.round(deal.discountPct)+' %';document.querySelector('#dealMerchants').textContent=String(deal.merchantCount);document.querySelector('#dealSaving').textContent=money(deal.saving);const cta=document.querySelector('#dealCta');cta.href=searchUrl(deal.name);cta.querySelector('span:first-child').textContent=t.compare;}
  function rerender(){applyCopy();renderDeal();}
  document.querySelector('#language')?.addEventListener('change',()=>queueMicrotask(rerender));
  applyCopy();
  if(root.FundBlickCatalog?.load)root.FundBlickCatalog.load().then(list=>{products=Array.isArray(list)?list:[];rerender();}).catch(()=>{products=[];renderDeal();});
  root.FundBlickHomeExtras={rerender};
})(typeof window!=='undefined'?window:null);
