'use strict';
(function(){
  const locales={
    de:{name:'Deutsch',speech:'de-DE',dir:'ltr'},
    tr:{name:'Türkçe',speech:'tr-TR',dir:'ltr'},
    ru:{name:'Русский',speech:'ru-RU',dir:'ltr'},
    ar:{name:'العربية',speech:'ar-SA',dir:'rtl'},
    pl:{name:'Polski',speech:'pl-PL',dir:'ltr'},
    ro:{name:'Română',speech:'ro-RO',dir:'ltr'},
    uk:{name:'Українська',speech:'uk-UA',dir:'ltr'},
    en:{name:'English',speech:'en-GB',dir:'ltr'},
    it:{name:'Italiano',speech:'it-IT',dir:'ltr'},
    bg:{name:'Български',speech:'bg-BG',dir:'ltr'},
    hr:{name:'Hrvatski',speech:'hr-HR',dir:'ltr'},
    el:{name:'Ελληνικά',speech:'el-GR',dir:'ltr'},
    sr:{name:'Српски',speech:'sr-RS',dir:'ltr'},
    es:{name:'Español',speech:'es-ES',dir:'ltr'},
    fr:{name:'Français',speech:'fr-FR',dir:'ltr'},
    pt:{name:'Português',speech:'pt-PT',dir:'ltr'},
    fa:{name:'فارسی',speech:'fa-IR',dir:'rtl'},
    sq:{name:'Shqip',speech:'sq-AL',dir:'ltr'},
    'zh-Hans':{name:'简体中文',speech:'zh-CN',dir:'ltr'},
    ku:{name:'Kurdî',speech:'ku-TR',dir:'ltr'}
  };
  const copy={
    de:{search:'Produkt, Marke oder Modell suchen …',button:'Suchen',eyebrow:'PRODUKTSUCHE · HÄNDLERPREISE',hero:'Suchen. Angebote vergleichen. Fertig.',lead:'Produkt eingeben – FundBlick zeigt aktuell angebundene Händlerangebote und die verfügbaren Preis- und Produktinformationen.',popular:'Zum Ausprobieren:',voiceStart:'Spracheingabe starten',voiceStop:'Spracheingabe beenden',listening:'Ich höre zu …',voiceError:'Spracheingabe nicht möglich. Bitte tippe deine Suche ein.'},
    tr:{search:'Ürün, marka veya model ara …',button:'Ara',eyebrow:'ÜRÜN ARAMA · SATICI FİYATLARI',hero:'Ara. Teklifleri karşılaştır. Tamam.',lead:'Ürünü gir — FundBlick bağlı mağaza tekliflerini ve mevcut fiyat ile ürün bilgilerini gösterir.',popular:'Deneyin:',voiceStart:'Sesli aramayı başlat',voiceStop:'Sesli aramayı durdur',listening:'Dinliyorum …',voiceError:'Sesli arama kullanılamıyor. Lütfen aramanızı yazın.'},
    ru:{search:'Товар, бренд или модель …',button:'Найти',eyebrow:'ПОИСК ТОВАРОВ · ЦЕНЫ ПРОДАВЦОВ',hero:'Найти. Сравнить предложения. Готово.',lead:'Введите товар — FundBlick покажет подключённые предложения продавцов и доступные данные о цене и товаре.',popular:'Попробуйте:',voiceStart:'Начать голосовой поиск',voiceStop:'Остановить голосовой поиск',listening:'Слушаю …',voiceError:'Голосовой поиск недоступен. Введите запрос вручную.'},
    ar:{search:'ابحث عن منتج أو علامة أو موديل …',button:'بحث',eyebrow:'بحث المنتجات · أسعار المتاجر',hero:'ابحث. قارن العروض. انتهى.',lead:'أدخل المنتج — يعرض FundBlick عروض التجار المتصلين وبيانات السعر والمنتج المتاحة.',popular:'جرّب:',voiceStart:'بدء البحث الصوتي',voiceStop:'إيقاف البحث الصوتي',listening:'أستمع …',voiceError:'البحث الصوتي غير متاح. اكتب بحثك من فضلك.'},
    pl:{search:'Szukaj produktu, marki lub modelu …',button:'Szukaj',eyebrow:'WYSZUKIWANIE PRODUKTÓW · CENY SPRZEDAWCÓW',hero:'Szukaj. Porównuj oferty. Gotowe.',lead:'Wpisz produkt — FundBlick pokaże podłączone oferty sprzedawców oraz dostępne dane o cenie i produkcie.',popular:'Wypróbuj:',voiceStart:'Rozpocznij wyszukiwanie głosowe',voiceStop:'Zatrzymaj wyszukiwanie głosowe',listening:'Słucham …',voiceError:'Wyszukiwanie głosowe jest niedostępne. Wpisz zapytanie.'},
    ro:{search:'Caută produs, marcă sau model …',button:'Caută',eyebrow:'CĂUTARE PRODUSE · PREȚURI COMERCIANȚI',hero:'Caută. Compară ofertele. Gata.',lead:'Introdu produsul — FundBlick afișează ofertele comercianților conectați și informațiile disponibile despre preț și produs.',popular:'Încearcă:',voiceStart:'Pornește căutarea vocală',voiceStop:'Oprește căutarea vocală',listening:'Ascult …',voiceError:'Căutarea vocală nu este disponibilă. Tastează căutarea.'},
    uk:{search:'Товар, бренд або модель …',button:'Знайти',eyebrow:'ПОШУК ТОВАРІВ · ЦІНИ ПРОДАВЦІВ',hero:'Знайти. Порівняти пропозиції. Готово.',lead:'Введіть товар — FundBlick покаже підключені пропозиції продавців і доступні дані про ціну та товар.',popular:'Спробуйте:',voiceStart:'Почати голосовий пошук',voiceStop:'Зупинити голосовий пошук',listening:'Слухаю …',voiceError:'Голосовий пошук недоступний. Введіть запит вручну.'},
    en:{search:'Search product, brand or model …',button:'Search',eyebrow:'PRODUCT SEARCH · MERCHANT PRICES',hero:'Search. Compare offers. Done.',lead:'Enter a product — FundBlick shows currently connected merchant offers and the available price and product information.',popular:'Try:',voiceStart:'Start voice search',voiceStop:'Stop voice search',listening:'Listening …',voiceError:'Voice search is unavailable. Please type your search.'},
    it:{search:'Cerca prodotto, marchio o modello …',button:'Cerca',eyebrow:'RICERCA PRODOTTI · PREZZI DEI RIVENDITORI',hero:'Cerca. Confronta le offerte. Fatto.',lead:'Inserisci un prodotto — FundBlick mostra le offerte dei rivenditori collegati e le informazioni disponibili su prezzo e prodotto.',popular:'Prova:',voiceStart:'Avvia ricerca vocale',voiceStop:'Ferma ricerca vocale',listening:'Ti ascolto …',voiceError:'La ricerca vocale non è disponibile. Digita la ricerca.'},
    bg:{search:'Търси продукт, марка или модел …',button:'Търси',eyebrow:'ТЪРСЕНЕ НА ПРОДУКТИ · ЦЕНИ НА ТЪРГОВЦИ',hero:'Търси. Сравни офертите. Готово.',lead:'Въведете продукт — FundBlick показва свързаните оферти на търговци и наличната информация за цена и продукт.',popular:'Опитай:',voiceStart:'Стартирай гласово търсене',voiceStop:'Спри гласовото търсене',listening:'Слушам …',voiceError:'Гласовото търсене не е достъпно. Въведи търсенето.'},
    hr:{search:'Traži proizvod, marku ili model …',button:'Traži',eyebrow:'PRETRAGA PROIZVODA · CIJENE TRGOVACA',hero:'Traži. Usporedi ponude. Gotovo.',lead:'Unesite proizvod — FundBlick prikazuje povezane ponude trgovaca te dostupne podatke o cijeni i proizvodu.',popular:'Isprobaj:',voiceStart:'Pokreni glasovno pretraživanje',voiceStop:'Zaustavi glasovno pretraživanje',listening:'Slušam …',voiceError:'Glasovno pretraživanje nije dostupno. Upiši pretragu.'},
    el:{search:'Αναζήτηση προϊόντος, μάρκας ή μοντέλου …',button:'Αναζήτηση',eyebrow:'ΑΝΑΖΗΤΗΣΗ ΠΡΟΪΟΝΤΩΝ · ΤΙΜΕΣ ΕΜΠΟΡΩΝ',hero:'Αναζήτησε. Σύγκρινε προσφορές. Έτοιμο.',lead:'Πληκτρολογήστε ένα προϊόν — το FundBlick εμφανίζει τις συνδεδεμένες προσφορές εμπόρων και τις διαθέσιμες πληροφορίες τιμής και προϊόντος.',popular:'Δοκίμασε:',voiceStart:'Έναρξη φωνητικής αναζήτησης',voiceStop:'Διακοπή φωνητικής αναζήτησης',listening:'Ακούω …',voiceError:'Η φωνητική αναζήτηση δεν είναι διαθέσιμη. Πληκτρολόγησε την αναζήτησή σου.'},
    sr:{search:'Тражи производ, бренд или модел …',button:'Тражи',eyebrow:'ПРЕТРАГА ПРОИЗВОДА · ЦЕНЕ ПРОДАВАЦА',hero:'Тражи. Упореди понуде. Готово.',lead:'Унесите производ — FundBlick приказује повезане понуде продаваца и доступне податке о цени и производу.',popular:'Пробај:',voiceStart:'Покрени гласовну претрагу',voiceStop:'Заустави гласовну претрагу',listening:'Слушам …',voiceError:'Гласовна претрага није доступна. Унеси претрагу.'},
    es:{search:'Buscar producto, marca o modelo …',button:'Buscar',eyebrow:'BÚSQUEDA DE PRODUCTOS · PRECIOS DE COMERCIOS',hero:'Busca. Compara ofertas. Listo.',lead:'Introduce un producto — FundBlick muestra las ofertas de comercios conectados y la información disponible de precio y producto.',popular:'Prueba:',voiceStart:'Iniciar búsqueda por voz',voiceStop:'Detener búsqueda por voz',listening:'Escuchando …',voiceError:'La búsqueda por voz no está disponible. Escribe tu búsqueda.'},
    fr:{search:'Rechercher un produit, une marque ou un modèle …',button:'Rechercher',eyebrow:'RECHERCHE PRODUITS · PRIX DES MARCHANDS',hero:'Rechercher. Comparer les offres. Terminé.',lead:'Saisissez un produit — FundBlick affiche les offres des marchands connectés et les informations disponibles sur le prix et le produit.',popular:'Essayez:',voiceStart:'Démarrer la recherche vocale',voiceStop:'Arrêter la recherche vocale',listening:'Je vous écoute …',voiceError:'La recherche vocale est indisponible. Saisissez votre recherche.'},
    pt:{search:'Pesquisar produto, marca ou modelo …',button:'Pesquisar',eyebrow:'PESQUISA DE PRODUTOS · PREÇOS DE LOJAS',hero:'Pesquisa. Compara ofertas. Feito.',lead:'Introduza um produto — o FundBlick mostra as ofertas das lojas ligadas e as informações disponíveis de preço e produto.',popular:'Experimenta:',voiceStart:'Iniciar pesquisa por voz',voiceStop:'Parar pesquisa por voz',listening:'A ouvir …',voiceError:'A pesquisa por voz não está disponível. Escreve a tua pesquisa.'},
    fa:{search:'جستجوی محصول، برند یا مدل …',button:'جستجو',eyebrow:'جستجوی محصول · قیمت فروشندگان',hero:'جستجو کن. پیشنهادها را مقایسه کن. تمام.',lead:'محصول را وارد کنید — FundBlick پیشنهادهای فروشندگان متصل و اطلاعات موجود درباره قیمت و محصول را نشان می‌دهد.',popular:'امتحان کنید:',voiceStart:'شروع جستجوی صوتی',voiceStop:'توقف جستجوی صوتی',listening:'گوش می‌دهم …',voiceError:'جستجوی صوتی در دسترس نیست. عبارت جستجو را تایپ کنید.'},
    sq:{search:'Kërko produkt, markë ose model …',button:'Kërko',eyebrow:'KËRKIM PRODUKTESH · ÇMIME SHITËSISH',hero:'Kërko. Krahaso ofertat. Gati.',lead:'Shkruaj produktin — FundBlick tregon ofertat e shitësve të lidhur dhe informacionin e disponueshëm për çmimin dhe produktin.',popular:'Provo:',voiceStart:'Fillo kërkimin me zë',voiceStop:'Ndalo kërkimin me zë',listening:'Po dëgjoj …',voiceError:'Kërkimi me zë nuk është i disponueshëm. Shkruaj kërkimin.'},
    'zh-Hans':{search:'搜索商品、品牌或型号 …',button:'搜索',eyebrow:'商品搜索 · 商家价格',hero:'搜索。比较报价。完成。',lead:'输入商品 — FundBlick 汇总不同商家的报价，并显示包含运费的总价。',popular:'试试：',voiceStart:'开始语音搜索',voiceStop:'停止语音搜索',listening:'正在聆听 …',voiceError:'语音搜索不可用。请手动输入搜索内容。'},
    ku:{search:'Hilber, marka an modelê bigere …',button:'Bigere',eyebrow:'LÊGERÎNA HILBERAN · BIHAYÊN FIROŞKARAN',hero:'Bigere. Pêşniyaran berawird bike. Qediya.',lead:'Hilberê binivîse — FundBlick pêşniyarên firoşkarên girêdayî û agahiyên berdest ên biha û hilberê nîşan dide.',popular:'Biceribîne:',voiceStart:'Lêgerîna dengî dest pê bike',voiceStop:'Lêgerîna dengî rawestîne',listening:'Ez guhdar dikim …',voiceError:'Lêgerîna dengî ne berdest e. Lêgerîna xwe binivîse.'}
  };
  const secondary={
    de:{multiMerchants:'Mehrere Händler',shippingIncluded:'Versand eingerechnet',noShopSearch:'Keine Shop-Suche nötig',howCompare:'So vergleicht FundBlick',sameProduct:'4 Händler für dasselbe Produkt',total:'Gesamt',priceDifference:'Preisunterschied',tryComparison:'Vergleich ausprobieren',imprint:'Impressum',privacy:'Datenschutz',developmentNote:'Development Preview · simulierte Daten'},
    tr:{multiMerchants:'Birden fazla satıcı',shippingIncluded:'Kargo dahil',noShopSearch:'Mağaza mağaza arama yok',howCompare:'FundBlick böyle karşılaştırır',sameProduct:'Aynı ürün için 4 satıcı',total:'Toplam',priceDifference:'Fiyat farkı',tryComparison:'Karşılaştırmayı dene',imprint:'Künye',privacy:'Gizlilik',developmentNote:'Geliştirme önizlemesi · simüle veriler'},
    ru:{multiMerchants:'Несколько продавцов',shippingIncluded:'Доставка учтена',noShopSearch:'Не нужно искать по магазинам',howCompare:'Как сравнивает FundBlick',sameProduct:'4 продавца одного товара',total:'Итого',priceDifference:'Разница в цене',tryComparison:'Попробовать сравнение',imprint:'Выходные данные',privacy:'Конфиденциальность',developmentNote:'Предпросмотр разработки · тестовые данные'},
    ar:{multiMerchants:'عدة متاجر',shippingIncluded:'الشحن محسوب',noShopSearch:'لا حاجة للبحث متجرًا متجرًا',howCompare:'هكذا يقارن FundBlick',sameProduct:'4 متاجر لنفس المنتج',total:'الإجمالي',priceDifference:'فرق السعر',tryComparison:'جرّب المقارنة',imprint:'البيانات القانونية',privacy:'الخصوصية',developmentNote:'معاينة التطوير · بيانات محاكاة'},
    pl:{multiMerchants:'Wielu sprzedawców',shippingIncluded:'Wysyłka uwzględniona',noShopSearch:'Bez szukania sklep po sklepie',howCompare:'Tak porównuje FundBlick',sameProduct:'4 sprzedawców tego samego produktu',total:'Razem',priceDifference:'Różnica ceny',tryComparison:'Wypróbuj porównanie',imprint:'Nota prawna',privacy:'Prywatność',developmentNote:'Podgląd rozwojowy · dane symulowane'},
    ro:{multiMerchants:'Mai mulți comercianți',shippingIncluded:'Livrare inclusă',noShopSearch:'Fără căutare magazin cu magazin',howCompare:'Așa compară FundBlick',sameProduct:'4 comercianți pentru același produs',total:'Total',priceDifference:'Diferență de preț',tryComparison:'Încearcă comparația',imprint:'Informații legale',privacy:'Confidențialitate',developmentNote:'Previzualizare dezvoltare · date simulate'},
    uk:{multiMerchants:'Кілька продавців',shippingIncluded:'Доставку враховано',noShopSearch:'Не треба шукати магазин за магазином',howCompare:'Як порівнює FundBlick',sameProduct:'4 продавці одного товару',total:'Разом',priceDifference:'Різниця в ціні',tryComparison:'Спробувати порівняння',imprint:'Вихідні дані',privacy:'Конфіденційність',developmentNote:'Попередній перегляд · симульовані дані'},
    en:{multiMerchants:'Multiple merchants',shippingIncluded:'Shipping included',noShopSearch:'No shop-by-shop search',howCompare:'How FundBlick compares',sameProduct:'4 merchants for the same product',total:'Total',priceDifference:'Price difference',tryComparison:'Try the comparison',imprint:'Legal notice',privacy:'Privacy',developmentNote:'Development preview · simulated data'},
    it:{multiMerchants:'Più rivenditori',shippingIncluded:'Spedizione inclusa',noShopSearch:'Niente ricerca negozio per negozio',howCompare:'Come confronta FundBlick',sameProduct:'4 rivenditori per lo stesso prodotto',total:'Totale',priceDifference:'Differenza di prezzo',tryComparison:'Prova il confronto',imprint:'Note legali',privacy:'Privacy',developmentNote:'Anteprima di sviluppo · dati simulati'},
    bg:{multiMerchants:'Няколко търговци',shippingIncluded:'Доставката е включена',noShopSearch:'Без търсене магазин по магазин',howCompare:'Как сравнява FundBlick',sameProduct:'4 търговци за същия продукт',total:'Общо',priceDifference:'Разлика в цената',tryComparison:'Изпробвай сравнението',imprint:'Правна информация',privacy:'Поверителност',developmentNote:'Преглед за разработка · симулирани данни'},
    hr:{multiMerchants:'Više trgovaca',shippingIncluded:'Dostava uključena',noShopSearch:'Bez pretraživanja trgovine po trgovine',howCompare:'Kako FundBlick uspoređuje',sameProduct:'4 trgovca za isti proizvod',total:'Ukupno',priceDifference:'Razlika u cijeni',tryComparison:'Isprobaj usporedbu',imprint:'Pravne informacije',privacy:'Privatnost',developmentNote:'Razvojni pregled · simulirani podaci'},
    el:{multiMerchants:'Πολλοί έμποροι',shippingIncluded:'Τα μεταφορικά περιλαμβάνονται',noShopSearch:'Χωρίς αναζήτηση κατάστημα-κατάστημα',howCompare:'Πώς συγκρίνει το FundBlick',sameProduct:'4 έμποροι για το ίδιο προϊόν',total:'Σύνολο',priceDifference:'Διαφορά τιμής',tryComparison:'Δοκίμασε τη σύγκριση',imprint:'Νομικές πληροφορίες',privacy:'Απόρρητο',developmentNote:'Προεπισκόπηση ανάπτυξης · προσομοιωμένα δεδομένα'},
    sr:{multiMerchants:'Више продаваца',shippingIncluded:'Достава је урачуната',noShopSearch:'Без претраге продавнице по продавнице',howCompare:'Како FundBlick пореди',sameProduct:'4 продавца за исти производ',total:'Укупно',priceDifference:'Разлика у цени',tryComparison:'Испробај поређење',imprint:'Правне информације',privacy:'Приватност',developmentNote:'Развојни преглед · симулирани подаци'},
    es:{multiMerchants:'Varios comercios',shippingIncluded:'Envío incluido',noShopSearch:'Sin buscar tienda por tienda',howCompare:'Así compara FundBlick',sameProduct:'4 comercios para el mismo producto',total:'Total',priceDifference:'Diferencia de precio',tryComparison:'Probar la comparación',imprint:'Aviso legal',privacy:'Privacidad',developmentNote:'Vista previa de desarrollo · datos simulados'},
    fr:{multiMerchants:'Plusieurs marchands',shippingIncluded:'Livraison incluse',noShopSearch:'Pas de recherche boutique par boutique',howCompare:'Comment FundBlick compare',sameProduct:'4 marchands pour le même produit',total:'Total',priceDifference:'Écart de prix',tryComparison:'Essayer la comparaison',imprint:'Mentions légales',privacy:'Confidentialité',developmentNote:'Aperçu de développement · données simulées'},
    pt:{multiMerchants:'Vários comerciantes',shippingIncluded:'Envio incluído',noShopSearch:'Sem pesquisar loja a loja',howCompare:'Como o FundBlick compara',sameProduct:'4 comerciantes para o mesmo produto',total:'Total',priceDifference:'Diferença de preço',tryComparison:'Experimentar a comparação',imprint:'Informação legal',privacy:'Privacidade',developmentNote:'Pré-visualização de desenvolvimento · dados simulados'},
    fa:{multiMerchants:'چند فروشنده',shippingIncluded:'ارسال محاسبه شده',noShopSearch:'بدون جستجوی فروشگاه به فروشگاه',howCompare:'FundBlick چگونه مقایسه می‌کند',sameProduct:'۴ فروشنده برای یک محصول',total:'مجموع',priceDifference:'اختلاف قیمت',tryComparison:'مقایسه را امتحان کنید',imprint:'اطلاعات قانونی',privacy:'حریم خصوصی',developmentNote:'پیش‌نمایش توسعه · داده‌های شبیه‌سازی‌شده'},
    sq:{multiMerchants:'Disa shitës',shippingIncluded:'Transporti i përfshirë',noShopSearch:'Pa kërkuar dyqan më dyqan',howCompare:'Si krahason FundBlick',sameProduct:'4 shitës për të njëjtin produkt',total:'Gjithsej',priceDifference:'Diferenca e çmimit',tryComparison:'Provo krahasimin',imprint:'Të dhëna ligjore',privacy:'Privatësia',developmentNote:'Pamje zhvillimi · të dhëna të simuluara'},
    'zh-Hans':{multiMerchants:'多个商家',shippingIncluded:'已计入运费',noShopSearch:'无需逐店搜索',howCompare:'FundBlick 如何比较',sameProduct:'同一商品的 4 个商家',total:'总价',priceDifference:'价格差',tryComparison:'试用比较',imprint:'法律信息',privacy:'隐私',developmentNote:'开发预览 · 模拟数据'},
    ku:{multiMerchants:'Çend firoşkar',shippingIncluded:'Barkirin tê de ye',noShopSearch:'Ne pêdivî ye dikan bi dikan bigerî',howCompare:'FundBlick çawa berawird dike',sameProduct:'4 firoşkar ji bo heman hilberê',total:'Tevahî',priceDifference:'Cûdahiya bihayê',tryComparison:'Berawirdkirinê biceribîne',imprint:'Agahiyên qanûnî',privacy:'Nepenî',developmentNote:'Pêşdîtina pêşvebirinê · daneyên simulasyonê'}
  };
  for(const [code,extra] of Object.entries(secondary))Object.assign(copy[code],extra);
  window.FUNDBLICK_LOCALES=Object.freeze(locales);
  window.FUNDBLICK_I18N=Object.freeze(copy);
})();
