'use strict';
/* The seven language settings mirror the private FundBlick language registry. */
(function () {
  const languages={de:{speech:'de-DE',dir:'ltr',locale:'de-DE'},ru:{speech:'ru-RU',dir:'ltr',locale:'ru-DE'},tr:{speech:'tr-TR',dir:'ltr',locale:'tr-DE'},uk:{speech:'uk-UA',dir:'ltr',locale:'uk-DE'},it:{speech:'it-IT',dir:'ltr',locale:'it-DE'},en:{speech:'en-GB',dir:'ltr',locale:'en-DE'},ar:{speech:'ar-SA',dir:'rtl',locale:'ar-EG'}};
  const copy={
    de:{navSearch:'Produktsuche',homeLink:'Startseite',eyebrow:'PRODUKTSUCHE',heroOne:'Finden, was passt.',heroTwo:'Vergleichen, was zählt.',intro:'Suche nach einem Produkt, einer Marke oder einer Eigenschaft. Verfeinere die Treffer anschließend mit passenden Filtern.',searchLabel:'Produkte suchen',searchPlaceholder:'Was suchst du?',resultPlaceholder:'Produkt, Marke oder Eigenschaft …',searchButton:'Suchen',categoryHeadphones:'🎧 Kopfhörer',categoryShoes:'👟 Schuhe',categoryBeauty:'✦ Beauty',categoryPhones:'📱 Smartphones',dataNote:'FundBlick befindet sich im Aufbau. Die derzeitigen Produkte sind Testdaten; es gibt noch keine kaufbaren Händlerangebote.',resultsNote:'Testdaten ohne kaufbare Händlerangebote. Angezeigte Preise enthalten keine nachgewiesenen Versandkosten.',results:'Suchergebnisse',sort:'Sortieren',relevance:'Beste Treffer',priceAsc:'Preis: aufsteigend',priceDesc:'Preis: absteigend',manufacturer:'Hersteller',refine:'Suche verfeinern',reset:'Alle Filter zurücksetzen',imprint:'Impressum',privacy:'Datenschutz',found:'Produkte gefunden',oneFound:'Produkt gefunden',price:'Preis der Testprodukte',from:'Von (€)',to:'Bis (€)',apply:'Preis anwenden',connection:'Verbindung',form:'Bauform',features:'Funktionen',battery:'Akkulaufzeit',screen:'Bildschirmdiagonale',panel:'Bildschirmtechnik',size:'Schuhgröße',color:'Farbe',storage:'Speicher',power:'Leistung',shipping:'Versand & Verfügbarkeit',shippingHelp:'Dazu liegen noch keine verlässlichen Daten vor. Diese Filter werden ergänzt, sobald Händlerangebote angebunden sind.',testData:'Testdaten',testPrice:'Testpreis, Versand unbekannt',noOffer:'Noch kein Angebot',noResults:'Keine passenden Produkte',noResultsHelp:'Ändere deine Suchbegriffe oder entferne einen Filter. Für manche Produktklassen liegen noch keine Testprodukte vor.',loadError:'Produktdaten konnten nicht geladen werden.',tryLater:'Bitte versuche es später erneut.',listening:'Ich höre zu …',voiceStart:'Spracheingabe starten',voiceStop:'Spracheingabe beenden',voiceError:'Spracheingabe nicht möglich. Bitte tippe deine Suche ein.'},
    en:{navSearch:'Product search',homeLink:'Home',eyebrow:'PRODUCT SEARCH',heroOne:'Find the right fit.',heroTwo:'Compare what matters.',intro:'Search for a product, brand or feature. Then refine the results with relevant filters.',searchLabel:'Search products',searchPlaceholder:'What are you looking for?',resultPlaceholder:'Product, brand or feature …',searchButton:'Search',categoryHeadphones:'🎧 Headphones',categoryShoes:'👟 Shoes',categoryBeauty:'✦ Beauty',categoryPhones:'📱 Smartphones',dataNote:'FundBlick is under construction. Current products are test data; there are no purchasable merchant offers yet.',resultsNote:'Test data without purchasable merchant offers. Shown prices do not include verified shipping costs.',results:'Search results',sort:'Sort',relevance:'Best match',priceAsc:'Price: low to high',priceDesc:'Price: high to low',manufacturer:'Brand',refine:'Refine search',reset:'Clear all filters',imprint:'Imprint',privacy:'Privacy',found:'products found',oneFound:'product found',price:'Test product price',from:'From (€)',to:'To (€)',apply:'Apply price',connection:'Connection',form:'Design',features:'Features',battery:'Battery life',screen:'Screen size',panel:'Panel',size:'Shoe size',color:'Color',storage:'Storage',power:'Power',shipping:'Shipping & availability',shippingHelp:'Reliable data is not yet available. These filters will follow when merchant offers are connected.',testData:'Test data',testPrice:'Test price, shipping unknown',noOffer:'No offer yet',noResults:'No matching products',noResultsHelp:'Change your search or remove a filter. Some product categories have no test products yet.',loadError:'Product data could not be loaded.',tryLater:'Please try again later.',listening:'Listening …',voiceStart:'Start voice search',voiceStop:'Stop voice search',voiceError:'Voice search is unavailable. Please type your search.'},
    ru:{navSearch:'Поиск товаров',homeLink:'Главная',eyebrow:'ПОИСК ТОВАРОВ',heroOne:'Найдите подходящее.',heroTwo:'Сравните важное.',intro:'Ищите товар, бренд или характеристику. Затем уточните результаты с помощью фильтров.',searchLabel:'Поиск товаров',searchPlaceholder:'Что вы ищете?',resultPlaceholder:'Товар, бренд или характеристика …',searchButton:'Найти',categoryHeadphones:'🎧 Наушники',categoryShoes:'👟 Обувь',categoryBeauty:'✦ Красота',categoryPhones:'📱 Смартфоны',dataNote:'FundBlick находится в разработке. Сейчас показаны тестовые товары; предложений для покупки пока нет.',resultsNote:'Тестовые данные без предложений для покупки. Указанные цены не включают подтверждённую стоимость доставки.',results:'Результаты поиска',sort:'Сортировка',relevance:'Лучшее совпадение',priceAsc:'Цена: по возрастанию',priceDesc:'Цена: по убыванию',manufacturer:'Бренд',refine:'Уточнить поиск',reset:'Сбросить фильтры',imprint:'Выходные данные',privacy:'Конфиденциальность',found:'товаров найдено',oneFound:'товар найден',price:'Цена тестовых товаров',from:'От (€)',to:'До (€)',apply:'Применить цену',connection:'Подключение',form:'Тип',features:'Функции',battery:'Время работы',screen:'Диагональ',panel:'Тип экрана',size:'Размер обуви',color:'Цвет',storage:'Память',power:'Мощность',shipping:'Доставка и наличие',shippingHelp:'Достоверных данных пока нет. Фильтры появятся после подключения предложений магазинов.',testData:'Тестовые данные',testPrice:'Тестовая цена, доставка неизвестна',noOffer:'Предложений пока нет',noResults:'Подходящих товаров нет',noResultsHelp:'Измените запрос или уберите фильтр. Для некоторых категорий тестовых товаров пока нет.',loadError:'Не удалось загрузить товары.',tryLater:'Повторите попытку позже.',listening:'Слушаю …',voiceStart:'Начать голосовой поиск',voiceStop:'Остановить голосовой поиск',voiceError:'Голосовой поиск недоступен. Введите запрос вручную.'},
    tr:{navSearch:'Ürün ara',homeLink:'Ana sayfa',eyebrow:'ÜRÜN ARAMA',heroOne:'Uygun olanı bulun.',heroTwo:'Önemli olanı karşılaştırın.',intro:'Ürün, marka veya özellik arayın. Sonuçları uygun filtrelerle daraltın.',searchLabel:'Ürün ara',searchPlaceholder:'Ne arıyorsunuz?',resultPlaceholder:'Ürün, marka veya özellik …',searchButton:'Ara',categoryHeadphones:'🎧 Kulaklık',categoryShoes:'👟 Ayakkabı',categoryBeauty:'✦ Güzellik',categoryPhones:'📱 Akıllı telefonlar',dataNote:'FundBlick geliştirme aşamasındadır. Mevcut ürünler test verileridir; henüz satın alınabilir mağaza teklifi yoktur.',resultsNote:'Satın alınabilir teklifi olmayan test verileri. Gösterilen fiyatlarda doğrulanmış kargo ücreti yoktur.',results:'Arama sonuçları',sort:'Sırala',relevance:'En uygun',priceAsc:'Fiyat: artan',priceDesc:'Fiyat: azalan',manufacturer:'Marka',refine:'Aramayı daralt',reset:'Filtreleri sıfırla',imprint:'Künye',privacy:'Gizlilik',found:'ürün bulundu',oneFound:'ürün bulundu',price:'Test ürünü fiyatı',from:'En az (€)',to:'En çok (€)',apply:'Fiyatı uygula',connection:'Bağlantı',form:'Tip',features:'Özellikler',battery:'Pil ömrü',screen:'Ekran boyutu',panel:'Panel',size:'Ayakkabı numarası',color:'Renk',storage:'Depolama',power:'Güç',shipping:'Kargo ve stok',shippingHelp:'Henüz güvenilir veri yok. Mağaza teklifleri bağlandığında filtreler eklenecek.',testData:'Test verisi',testPrice:'Test fiyatı, kargo bilinmiyor',noOffer:'Henüz teklif yok',noResults:'Uygun ürün yok',noResultsHelp:'Aramanızı değiştirin veya filtreyi kaldırın. Bazı kategorilerde henüz test ürünü yok.',loadError:'Ürün verileri yüklenemedi.',tryLater:'Lütfen daha sonra tekrar deneyin.',listening:'Dinliyorum …',voiceStart:'Sesli aramayı başlat',voiceStop:'Sesli aramayı durdur',voiceError:'Sesli arama kullanılamıyor. Lütfen yazarak arayın.'},
    uk:{navSearch:'Пошук товарів',homeLink:'Головна',eyebrow:'ПОШУК ТОВАРІВ',heroOne:'Знайдіть потрібне.',heroTwo:'Порівняйте важливе.',intro:'Шукайте товар, бренд або характеристику. Потім уточніть результати відповідними фільтрами.',searchLabel:'Пошук товарів',searchPlaceholder:'Що ви шукаєте?',resultPlaceholder:'Товар, бренд або характеристика …',searchButton:'Шукати',categoryHeadphones:'🎧 Навушники',categoryShoes:'👟 Взуття',categoryBeauty:'✦ Краса',categoryPhones:'📱 Смартфони',dataNote:'FundBlick розробляється. Зараз показано тестові товари; пропозицій для купівлі ще немає.',resultsNote:'Тестові дані без пропозицій для купівлі. Указані ціни не містять підтвердженої вартості доставки.',results:'Результати пошуку',sort:'Сортування',relevance:'Найкращий збіг',priceAsc:'Ціна: за зростанням',priceDesc:'Ціна: за спаданням',manufacturer:'Бренд',refine:'Уточнити пошук',reset:'Скинути фільтри',imprint:'Вихідні дані',privacy:'Конфіденційність',found:'товарів знайдено',oneFound:'товар знайдено',price:'Ціна тестових товарів',from:'Від (€)',to:'До (€)',apply:'Застосувати ціну',connection:'Підключення',form:'Тип',features:'Функції',battery:'Час роботи',screen:'Діагональ',panel:'Тип екрана',size:'Розмір взуття',color:'Колір',storage:'Пам’ять',power:'Потужність',shipping:'Доставка й наявність',shippingHelp:'Надійних даних поки немає. Фільтри з’являться після підключення магазинів.',testData:'Тестові дані',testPrice:'Тестова ціна, доставка невідома',noOffer:'Пропозицій ще немає',noResults:'Відповідних товарів немає',noResultsHelp:'Змініть запит або приберіть фільтр. Для деяких категорій тестових товарів ще немає.',loadError:'Не вдалося завантажити товари.',tryLater:'Повторіть спробу пізніше.',listening:'Слухаю …',voiceStart:'Почати голосовий пошук',voiceStop:'Зупинити голосовий пошук',voiceError:'Голосовий пошук недоступний. Введіть запит вручну.'},
    it:{navSearch:'Cerca prodotti',homeLink:'Home',eyebrow:'RICERCA PRODOTTI',heroOne:'Trova quello giusto.',heroTwo:'Confronta ciò che conta.',intro:'Cerca un prodotto, un marchio o una caratteristica. Poi affina i risultati con i filtri.',searchLabel:'Cerca prodotti',searchPlaceholder:'Cosa cerchi?',resultPlaceholder:'Prodotto, marchio o caratteristica …',searchButton:'Cerca',categoryHeadphones:'🎧 Cuffie',categoryShoes:'👟 Scarpe',categoryBeauty:'✦ Bellezza',categoryPhones:'📱 Smartphone',dataNote:'FundBlick è in fase di sviluppo. I prodotti attuali sono dati di prova; non ci sono ancora offerte acquistabili.',resultsNote:'Dati di prova senza offerte acquistabili. I prezzi indicati non includono spese di spedizione verificate.',results:'Risultati di ricerca',sort:'Ordina',relevance:'Più pertinenti',priceAsc:'Prezzo: crescente',priceDesc:'Prezzo: decrescente',manufacturer:'Marchio',refine:'Affina la ricerca',reset:'Rimuovi tutti i filtri',imprint:'Note legali',privacy:'Privacy',found:'prodotti trovati',oneFound:'prodotto trovato',price:'Prezzo dei prodotti di prova',from:'Da (€)',to:'A (€)',apply:'Applica prezzo',connection:'Connessione',form:'Tipo',features:'Funzioni',battery:'Autonomia',screen:'Dimensione schermo',panel:'Tecnologia schermo',size:'Numero scarpe',color:'Colore',storage:'Memoria',power:'Potenza',shipping:'Spedizione e disponibilità',shippingHelp:'Non ci sono ancora dati affidabili. I filtri saranno aggiunti con le offerte dei negozi.',testData:'Dati di prova',testPrice:'Prezzo di prova, spedizione ignota',noOffer:'Nessuna offerta',noResults:'Nessun prodotto trovato',noResultsHelp:'Cambia la ricerca o rimuovi un filtro. Alcune categorie non hanno ancora prodotti di prova.',loadError:'Impossibile caricare i prodotti.',tryLater:'Riprova più tardi.',listening:'Ti ascolto …',voiceStart:'Avvia ricerca vocale',voiceStop:'Ferma ricerca vocale',voiceError:'Ricerca vocale non disponibile. Digita la ricerca.'},
    ar:{navSearch:'بحث المنتجات',homeLink:'الرئيسية',eyebrow:'بحث المنتجات',heroOne:'اعثر على ما يناسبك.',heroTwo:'قارن ما يهمك.',intro:'ابحث عن منتج أو علامة تجارية أو ميزة، ثم استخدم الفلاتر لتحديد النتائج.',searchLabel:'بحث المنتجات',searchPlaceholder:'عمّ تبحث؟',resultPlaceholder:'منتج أو علامة أو ميزة …',searchButton:'بحث',categoryHeadphones:'🎧 سماعات',categoryShoes:'👟 أحذية',categoryBeauty:'✦ مستحضرات تجميل',categoryPhones:'📱 هواتف ذكية',dataNote:'ما زال FundBlick قيد التطوير. المنتجات الحالية بيانات تجريبية، ولا توجد عروض شراء من المتاجر بعد.',resultsNote:'بيانات تجريبية بلا عروض شراء. الأسعار المعروضة لا تشمل تكاليف شحن مؤكدة.',results:'نتائج البحث',sort:'ترتيب',relevance:'الأكثر صلة',priceAsc:'السعر: الأقل أولاً',priceDesc:'السعر: الأعلى أولاً',manufacturer:'العلامة التجارية',refine:'تصفية البحث',reset:'إزالة جميع الفلاتر',imprint:'بيانات الناشر',privacy:'الخصوصية',found:'منتجات',oneFound:'منتج واحد',price:'سعر المنتجات التجريبية',from:'من (€)',to:'إلى (€)',apply:'تطبيق السعر',connection:'الاتصال',form:'النوع',features:'الميزات',battery:'عمر البطارية',screen:'حجم الشاشة',panel:'نوع الشاشة',size:'مقاس الحذاء',color:'اللون',storage:'السعة',power:'القدرة',shipping:'الشحن والتوفر',shippingHelp:'لا تتوفر بيانات موثوقة بعد. ستضاف الفلاتر عند ربط عروض المتاجر.',testData:'بيانات تجريبية',testPrice:'سعر تجريبي، الشحن غير معروف',noOffer:'لا توجد عروض بعد',noResults:'لا توجد منتجات مطابقة',noResultsHelp:'غيّر كلمات البحث أو أزل أحد الفلاتر. لا تتوفر منتجات تجريبية لبعض الفئات بعد.',loadError:'تعذر تحميل بيانات المنتجات.',tryLater:'حاول مجدداً لاحقاً.',listening:'أستمع إليك …',voiceStart:'بدء البحث الصوتي',voiceStop:'إيقاف البحث الصوتي',voiceError:'البحث الصوتي غير متاح. اكتب كلمات البحث.'}
  };
  const params=new URLSearchParams(location.search),requested=params.get('lang');
  const accessibility={de:['Zum Inhalt','Sprache wählen','Produktbereiche','Rechtliches','Aktive Filter','Produkte'],ru:['К содержимому','Выбрать язык','Категории товаров','Правовая информация','Активные фильтры','Товары'],tr:['İçeriğe geç','Dil seç','Ürün kategorileri','Yasal bilgiler','Etkin filtreler','Ürünler'],uk:['До вмісту','Вибрати мову','Категорії товарів','Правова інформація','Активні фільтри','Товари'],it:['Vai al contenuto','Scegli lingua','Categorie prodotti','Informazioni legali','Filtri attivi','Prodotti'],en:['Skip to content','Choose language','Product categories','Legal information','Active filters','Products'],ar:['انتقل إلى المحتوى','اختر اللغة','فئات المنتجات','معلومات قانونية','الفلاتر النشطة','المنتجات']};
  const voiceNotes={de:'Optional: Der Browser kann Sprache zur Erkennung an einen externen Dienst senden. Erst der Klick auf das Mikrofon startet die Aufnahme.',ru:'Необязательно: браузер может отправлять голос во внешний сервис для распознавания. Запись начинается только после нажатия на микрофон.',tr:'İsteğe bağlı: Tarayıcı sesinizi tanıma için harici bir hizmete gönderebilir. Kayıt yalnızca mikrofona dokununca başlar.',uk:'Необов’язково: браузер може надсилати голос до зовнішньої служби розпізнавання. Запис починається лише після натискання на мікрофон.',it:'Facoltativo: il browser può inviare la voce a un servizio esterno per il riconoscimento. La registrazione inizia solo dopo aver premuto il microfono.',en:'Optional: Your browser may send speech to an external recognition service. Recording starts only when you press the microphone.',ar:'اختياري: قد يرسل المتصفح صوتك إلى خدمة خارجية للتعرّف عليه. يبدأ التسجيل فقط عند الضغط على الميكروفون.'};
  let saved='de';try{saved=localStorage.getItem('fundblick-language')||'de'}catch{}
  const lang=languages[requested]?requested:languages[saved]?saved:'de';
  const t=copy[lang],config=languages[lang];
  window.FundBlickLanguage={lang,config,t,translate:(key)=>t[key]||copy.de[key]||key};
  document.documentElement.lang=lang;document.documentElement.dir=config.dir;
  document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t[el.dataset.i18n]||copy.de[el.dataset.i18n]||el.textContent});
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{el.placeholder=t[el.dataset.i18nPlaceholder]||copy.de[el.dataset.i18nPlaceholder]||el.placeholder});
  const labels=accessibility[lang];const skip=document.querySelector('.skip');if(skip)skip.textContent=labels[0];
  for(const [selector,label] of [['.categories',labels[2]],['.footer nav',labels[3]],['#chips',labels[4]],['.results-layout section[aria-label]',labels[5]]]){const el=document.querySelector(selector);if(el)el.setAttribute('aria-label',label)}
  const select=document.querySelector('#language');
  if(select){select.value=lang;select.setAttribute('aria-label',labels[1]);const selectLabel=document.querySelector('label[for=language]');if(selectLabel)selectLabel.textContent=labels[1];select.addEventListener('change',()=>{try{localStorage.setItem('fundblick-language',select.value)}catch{}const url=new URL(location.href);url.searchParams.set('lang',select.value);location.assign(url.href)})}
  document.querySelectorAll('a[href^="search.html"]').forEach(el=>{const url=new URL(el.href);url.searchParams.set('lang',lang);el.href=url.href});
  for(const form of document.querySelectorAll('.search-form')){const hidden=document.createElement('input');hidden.type='hidden';hidden.name='lang';hidden.value=lang;form.append(hidden)}
  const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;
  document.querySelectorAll('[data-voice-for]').forEach(button=>{
    if(!Speech||!window.isSecureContext)return;
    const input=document.getElementById(button.dataset.voiceFor),status=document.getElementById('voice-status');
    if(!input)return;
    button.hidden=false;button.setAttribute('aria-label',t.voiceStart);button.title=t.voiceStart;const disclosure=document.querySelector('.voice-disclosure');if(disclosure){disclosure.textContent=voiceNotes[lang];disclosure.hidden=false}
    let recognition=null,active=false,hadError=false;
    function finish(){active=false;button.classList.remove('listening');button.setAttribute('aria-label',t.voiceStart);button.title=t.voiceStart;if(status&&!hadError)status.textContent=''}
    button.addEventListener('click',()=>{
      if(active){recognition.stop();return}
      hadError=false;recognition=new Speech();recognition.lang=config.speech;recognition.interimResults=false;recognition.maxAlternatives=1;
      recognition.onresult=event=>{const transcript=event.results?.[0]?.[0]?.transcript?.trim();if(transcript){input.value=transcript;input.focus();input.dispatchEvent(new Event('input',{bubbles:true}))}};
      recognition.onerror=()=>{hadError=true;finish();if(status)status.textContent=t.voiceError};recognition.onend=finish;
      try{recognition.start();active=true;button.classList.add('listening');button.setAttribute('aria-label',t.voiceStop);button.title=t.voiceStop;if(status)status.textContent=t.listening}catch{hadError=true;finish();if(status)status.textContent=t.voiceError}
    });
  });
})();
