'use strict';
const FB_PRODUCTS=[
{id:'jlab-studio',name:'Studio Pro Wireless',brand:'JLab',price:62.89,form:'Over-Ear',shippingFree:true,stock:true,days:2,rating:4.4,color:'Schwarz',features:['Multipoint','Mikrofon','Faltbar'],battery:40,merchants:4},
{id:'jbl-770',name:'Tune 770NC',brand:'JBL',price:69.90,form:'Over-Ear',shippingFree:true,stock:true,days:2,rating:4.6,color:'Schwarz',features:['Active Noise Cancelling','Multipoint','Mikrofon','Faltbar'],battery:70,merchants:6},
{id:'sony-720',name:'WH-CH720N',brand:'Sony',price:79.00,form:'Over-Ear',shippingFree:false,stock:true,days:3,rating:4.5,color:'Schwarz',features:['Active Noise Cancelling','Multipoint','Mikrofon'],battery:35,merchants:5},
{id:'soundcore-q45',name:'Space Q45',brand:'Anker Soundcore',price:99.99,form:'Over-Ear',shippingFree:true,stock:true,days:1,rating:4.6,color:'Blau',features:['Active Noise Cancelling','Multipoint','Mikrofon','Faltbar'],battery:65,merchants:5},
{id:'senn-450',name:'HD 450BT',brand:'Sennheiser',price:89.90,form:'Over-Ear',shippingFree:true,stock:false,days:5,rating:4.3,color:'Weiß',features:['Active Noise Cancelling','Mikrofon','Faltbar'],battery:30,merchants:3},
{id:'sony-c520',name:'WF-C520',brand:'Sony',price:54.90,form:'In-Ear',shippingFree:true,stock:true,days:2,rating:4.2,color:'Weiß',features:['Multipoint','Mikrofon'],battery:22,merchants:6},
{id:'jbl-buds',name:'Live Buds 3',brand:'JBL',price:129.00,form:'In-Ear',shippingFree:false,stock:true,days:4,rating:4.5,color:'Schwarz',features:['Active Noise Cancelling','Multipoint','Mikrofon'],battery:40,merchants:4},
{id:'jlab-go',name:'Go Air Pop',brand:'JLab',price:29.99,form:'In-Ear',shippingFree:false,stock:true,days:2,rating:4.1,color:'Blau',features:['Mikrofon'],battery:32,merchants:3},
{id:'sony-520',name:'WH-CH520',brand:'Sony',price:39.90,form:'On-Ear',shippingFree:true,stock:true,days:1,rating:4.5,color:'Blau',features:['Multipoint','Mikrofon'],battery:50,merchants:7},
{id:'jbl-520',name:'Tune 520BT',brand:'JBL',price:34.90,form:'On-Ear',shippingFree:true,stock:true,days:3,rating:4.4,color:'Weiß',features:['Mikrofon','Faltbar'],battery:57,merchants:5}
];
const state={priceMin:null,priceMax:100,brands:new Set(),forms:new Set(['Over-Ear']),shippingFree:false,stock:false,fast:false,rating:null,colors:new Set(),features:new Set(),battery:null,minMerchants:null};
function money(n){return n.toLocaleString('de-DE',{style:'currency',currency:'EUR'})}
function matches(p,s=state){if(s.priceMin!=null&&p.price<s.priceMin)return false;if(s.priceMax!=null&&p.price>s.priceMax)return false;if(s.brands.size&&!s.brands.has(p.brand))return false;if(s.forms.size&&!s.forms.has(p.form))return false;if(s.shippingFree&&!p.shippingFree)return false;if(s.stock&&!p.stock)return false;if(s.fast&&p.days>3)return false;if(s.rating&&p.rating<s.rating)return false;if(s.colors.size&&!s.colors.has(p.color))return false;if(s.features.size&&![...s.features].every(x=>p.features.includes(x)))return false;if(s.battery&&p.battery<s.battery)return false;if(s.minMerchants&&p.merchants<s.minMerchants)return false;return true}
function filtered(){return FB_PRODUCTS.filter(p=>matches(p))}
function read(container){const num=v=>v===''?null:Number(v);state.priceMin=num(container.querySelector('.priceMin')?.value??'');state.priceMax=num(container.querySelector('.priceMax')?.value??'');const checked=sel=>[...container.querySelectorAll(sel+':checked')].map(i=>i.dataset.value);state.brands=new Set(checked('[data-facet="brand"]'));state.forms=new Set(checked('[data-facet="form"]'));state.colors=new Set(checked('[data-facet="color"]'));state.features=new Set(checked('[data-facet="feature"]'));state.shippingFree=!!container.querySelector('[data-facet="shipping"]:checked');state.stock=!!container.querySelector('[data-facet="stock"]:checked');state.fast=!!container.querySelector('[data-facet="fast"]:checked');state.rating=num(container.querySelector('[data-facet="rating"]:checked')?.dataset.value??'');state.battery=num(container.querySelector('[data-facet="battery"]:checked')?.dataset.value??'');state.minMerchants=num(container.querySelector('[data-facet="merchants"]:checked')?.dataset.value??'')}
function sync(from){document.querySelectorAll('#desktopFacetContent,#mobileFacetContent').forEach(c=>{if(c===from)return;c.querySelector('.priceMin').value=state.priceMin??'';c.querySelector('.priceMax').value=state.priceMax??'';c.querySelectorAll('[data-facet]').forEach(i=>{const f=i.dataset.facet,v=i.dataset.value;i.checked=f==='brand'?state.brands.has(v):f==='form'?state.forms.has(v):f==='color'?state.colors.has(v):f==='feature'?state.features.has(v):f==='shipping'?state.shippingFree:f==='stock'?state.stock:f==='fast'?state.fast:f==='rating'?Number(v)===state.rating:f==='battery'?Number(v)===state.battery:f==='merchants'?Number(v)===state.minMerchants:false})})}
function activeCount(){return (state.priceMin!=null||state.priceMax!=null?1:0)+state.brands.size+state.forms.size+state.colors.size+state.features.size+[state.shippingFree,state.stock,state.fast,!!state.rating,!!state.battery,!!state.minMerchants].filter(Boolean).length}
function chips(){const a=[];if(state.priceMin!=null||state.priceMax!=null)a.push(['price','Gesamtpreis: '+(state.priceMin!=null?money(state.priceMin)+' – ':'bis ')+(state.priceMax!=null?money(state.priceMax):'offen')]);state.brands.forEach(x=>a.push(['brand:'+x,'Hersteller: '+x]));state.forms.forEach(x=>a.push(['form:'+x,'Bauform: '+x]));if(state.shippingFree)a.push(['shipping','Kostenloser Versand']);if(state.stock)a.push(['stock','Sofort lieferbar']);if(state.fast)a.push(['fast','Lieferung ≤ 3 Tage']);if(state.rating)a.push(['rating','Bewertung ab '+state.rating]);state.colors.forEach(x=>a.push(['color:'+x,'Farbe: '+x]));state.features.forEach(x=>a.push(['feature:'+x,x]));if(state.battery)a.push(['battery','Akku ab '+state.battery+' h']);if(state.minMerchants)a.push(['merchants','Mind. '+state.minMerchants+' Händler']);return a}
function render(){const products=filtered(),count=products.length;document.querySelector('#resultCount').textContent=count;document.querySelector('#drawerCount').textContent=count;document.querySelector('#mobileFilterCount').textContent=activeCount();const ap=document.querySelector('#applied');ap.innerHTML=chips().map(([k,v])=>`<button type="button" data-key="${k}">${v} ×</button>`).join('')+(chips().length?'<button class="clear" type="button" id="clearFilters">Alle Filter löschen</button>':'<span style="font-size:12px;color:var(--muted);padding:9px 0">Keine Filter aktiv</span>');ap.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>remove(b.dataset.key));ap.querySelector('#clearFilters')?.addEventListener('click',clear);document.querySelectorAll('.cards .card').forEach(card=>{const id=card.dataset.product;card.hidden=id&&!products.some(p=>p.id===id)});updateCounts()}
function remove(k){if(k==='price'){state.priceMin=null;state.priceMax=null}else if(k==='shipping')state.shippingFree=false;else if(k==='stock')state.stock=false;else if(k==='fast')state.fast=false;else if(k==='rating')state.rating=null;else if(k==='battery')state.battery=null;else if(k==='merchants')state.minMerchants=null;else{const [f,v]=k.split(':');({brand:state.brands,form:state.forms,color:state.colors,feature:state.features}[f])?.delete(v)}sync(null);render()}
function clear(){state.priceMin=null;state.priceMax=null;state.brands.clear();state.forms.clear();state.colors.clear();state.features.clear();state.shippingFree=state.stock=state.fast=false;state.rating=state.battery=state.minMerchants=null;sync(null);render()}
function updateCounts(){document.querySelectorAll('[data-facet]').forEach(i=>{const label=i.closest('label'),count=label?.querySelector('.filter-count');if(!count)return;const clone={...state,brands:new Set(state.brands),forms:new Set(state.forms),colors:new Set(state.colors),features:new Set(state.features)};const f=i.dataset.facet,v=i.dataset.value;if(f==='brand'){clone.brands.add(v)}else if(f==='form'){clone.forms.add(v)}else if(f==='color'){clone.colors.add(v)}else if(f==='feature'){clone.features.add(v)}else if(f==='shipping')clone.shippingFree=true;else if(f==='stock')clone.stock=true;else if(f==='fast')clone.fast=true;else if(f==='rating')clone.rating=Number(v);else if(f==='battery')clone.battery=Number(v);else if(f==='merchants')clone.minMerchants=Number(v);count.textContent=FB_PRODUCTS.filter(p=>matches(p,clone)).length})}
function bind(){document.querySelectorAll('#desktopFacetContent,#mobileFacetContent').forEach(c=>{c.addEventListener('change',()=>{read(c);sync(c);if(c.id==='desktopFacetContent')render();else{const n=filtered().length;document.querySelector('#drawerCount').textContent=n}});c.querySelectorAll('.priceMin,.priceMax').forEach(i=>i.addEventListener('input',()=>{read(c);sync(c);if(c.id==='desktopFacetContent')render();else document.querySelector('#drawerCount').textContent=filtered().length}));c.querySelectorAll('.quick-ranges button').forEach(b=>b.addEventListener('click',()=>{const min=c.querySelector('.priceMin'),max=c.querySelector('.priceMax'),t=b.textContent;if(t.includes('bis 50')){min.value='';max.value='50'}else if(t.includes('50–100')){min.value='50';max.value='100'}else{min.value='100';max.value='200'}read(c);sync(c);if(c.id==='desktopFacetContent')render();else document.querySelector('#drawerCount').textContent=filtered().length}))});document.querySelectorAll('.clearAll').forEach(b=>b.onclick=clear);document.querySelector('.drawer-apply')?.addEventListener('click',render)}
window.FB_FACETS={bind,render,clear};