'use strict';
(function(){
  const locales={
    de:{name:'Deutsch',speech:'de-DE',dir:'ltr'},
    tr:{name:'Türkçe',speech:'tr-TR',dir:'ltr'},
    ru:{name:'Русский',speech:'ru-RU',dir:'ltr'},
    ar:{name:'العربية',speech:'ar-SA',dir:'rtl'},
    pl:{name:'Polski',speech:'pl-PL',dir:'ltr'},
    ro:{name:'Română',speech:'ro-RO',dir:'ltr'},
    uk:{name:'Українська',speech:'uk-UA',dir:'ltr'},
    en:{name:'English',speech:'en-GB',dir:'ltr'},
    it:{name:'Italiano',speech:'it-IT',dir:'ltr'},
    bg:{name:'Български',speech:'bg-BG',dir:'ltr'},
    hr:{name:'Hrvatski',speech:'hr-HR',dir:'ltr'},
    el:{name:'Ελληνικά',speech:'el-GR',dir:'ltr'},
    sr:{name:'Српски',speech:'sr-RS',dir:'ltr'},
    es:{name:'Español',speech:'es-ES',dir:'ltr'},
    fr:{name:'Français',speech:'fr-FR',dir:'ltr'},
    pt:{name:'Português',speech:'pt-PT',dir:'ltr'},
    fa:{name:'فارسی',speech:'fa-IR',dir:'rtl'},
    sq:{name:'Shqip',speech:'sq-AL',dir:'ltr'},
    'zh-Hans':{name:'简体中文',speech:'zh-CN',dir:'ltr'},
    ku:{name:'Kurdî',speech:'ku-TR',dir:'ltr'}
  };
  const copy={
    de:{search:'Produkt, Marke oder Modell suchen …',button:'Suchen',eyebrow:'PRODUKTSUCHE · HÄNDLERPREISE',hero:'Suchen. Angebote vergleichen. Fertig.',lead:'Produkt eingeben – FundBlick bündelt Angebote verschiedener Händler und zeigt dir den Gesamtpreis inklusive Versand.',popular:'Zum Ausprobieren:',voiceStart:'Spracheingabe starten',voiceStop:'Spracheingabe beenden',listening:'Ich höre zu …',voiceError:'Spracheingabe nicht möglich. Bitte tippe deine Suche ein.'},
    tr:{search:'Ürün, marka veya model ara …',button:'Ara',eyebrow:'ÜRÜN ARAMA · SATICI FİYATLARI',hero:'Ara. Teklifleri karşılaştır. Tamam.',lead:'Ürünü yaz — FundBlick farklı satıcıların tekliflerini bir araya getirir ve kargo dahil toplam fiyatı gösterir.',popular:'Deneyin:',voiceStart:'Sesli aramayı başlat',voiceStop:'Sesli aramayı durdur',listening:'Dinliyorum …',voiceError:'Sesli arama kullanılamıyor. Lütfen aramanızı yazın.'},
    ru:{search:'Товар, бренд или модель …',button:'Найти',eyebrow:'ПОИСК ТОВАРОВ · ЦЕНЫ ПРОДАВЦОВ',hero:'Найти. Сравнить предложения. Готово.',lead:'Введите товар — FundBlick объединит предложения разных продавцов и покажет полную цену с учётом доставки.',popular:'Попробуйте:',voiceStart:'Начать голосовой поиск',voiceStop:'Остановить голосовой поиск',listening:'Слушаю …',voiceError:'Голосовой поиск недоступен. Введите запрос вручную.'},
    ar:{search:'ابحث عن منتج أو علامة أو موديل …',button:'بحث',eyebrow:'بحث المنتجات · أسعار المتاجر',hero:'ابحث. قارن العروض. انتهى.',lead:'أدخل المنتج — يجمع FundBlick عروض متاجر مختلفة ويعرض السعر الإجمالي بما في ذلك الشحن.',popular:'جرّب:',voiceStart:'بدء البحث الصوتي',voiceStop:'إيقاف البحث الصوتي',listening:'أستمع …',voiceError:'البحث الصوتي غير متاح. اكتب بحثك من فضلك.'},
    pl:{search:'Szukaj produktu, marki lub modelu …',button:'Szukaj',eyebrow:'WYSZUKIWANIE PRODUKTÓW · CENY SPRZEDAWCÓW',hero:'Szukaj. Porównuj oferty. Gotowe.',lead:'Wpisz produkt — FundBlick łączy oferty różnych sprzedawców i pokazuje cenę całkowitą z wysyłką.',popular:'Wypróbuj:',voiceStart:'Rozpocznij wyszukiwanie głosowe',voiceStop:'Zatrzymaj wyszukiwanie głosowe',listening:'Słucham …',voiceError:'Wyszukiwanie głosowe jest niedostępne. Wpisz zapytanie.'},
    ro:{search:'Caută produs, marcă sau model …',button:'Caută',eyebrow:'CĂUTARE PRODUSE · PREȚURI COMERCIANȚI',hero:'Caută. Compară ofertele. Gata.',lead:'Introdu produsul — FundBlick reunește ofertele mai multor comercianți și arată prețul total, inclusiv livrarea.',popular:'Încearcă:',voiceStart:'Pornește căutarea vocală',voiceStop:'Oprește căutarea vocală',listening:'Ascult …',voiceError:'Căutarea vocală nu este disponibilă. Tastează căutarea.'},
    uk:{search:'Товар, бренд або модель …',button:'Знайти',eyebrow:'ПОШУК ТОВАРІВ · ЦІНИ ПРОДАВЦІВ',hero:'Знайти. Порівняти пропозиції. Готово.',lead:'Введіть товар — FundBlick об’єднає пропозиції різних продавців і покаже повну ціну з доставкою.',popular:'Спробуйте:',voiceStart:'Почати голосовий пошук',voiceStop:'Зупинити голосовий пошук',listening:'Слухаю …',voiceError:'Голосовий пошук недоступний. Введіть запит вручну.'},
    en:{search:'Search product, brand or model …',button:'Search',eyebrow:'PRODUCT SEARCH · MERCHANT PRICES',hero:'Search. Compare offers. Done.',lead:'Enter a product — FundBlick groups offers from different merchants and shows the total price including shipping.',popular:'Try:',voiceStart:'Start voice search',voiceStop:'Stop voice search',listening:'Listening …',voiceError:'Voice search is unavailable. Please type your search.'},
    it:{search:'Cerca prodotto, marchio o modello …',button:'Cerca',eyebrow:'RICERCA PRODOTTI · PREZZI DEI RIVENDITORI',hero:'Cerca. Confronta le offerte. Fatto.',lead:'Inserisci un prodotto — FundBlick riunisce le offerte di diversi rivenditori e mostra il prezzo totale, spedizione inclusa.',popular:'Prova:',voiceStart:'Avvia ricerca vocale',voiceStop:'Ferma ricerca vocale',listening:'Ti ascolto …',voiceError:'La ricerca vocale non è disponibile. Digita la ricerca.'},
    bg:{search:'Търси продукт, марка или модел …',button:'Търси',eyebrow:'ТЪРСЕНЕ НА ПРОДУКТИ · ЦЕНИ НА ТЪРГОВЦИ',hero:'Търси. Сравни офертите. Готово.',lead:'Въведи продукт — FundBlick събира оферти от различни търговци и показва общата цена с доставката.',popular:'Опитай:',voiceStart:'Стартирай гласово търсене',voiceStop:'Спри гласовото търсене',listening:'Слушам …',voiceError:'Гласовото търсене не е достъпно. Въведи търсенето.'},
    hr:{search:'Traži proizvod, marku ili model …',button:'Traži',eyebrow:'PRETRAGA PROIZVODA · CIJENE TRGOVACA',hero:'Traži. Usporedi ponude. Gotovo.',lead:'Unesi proizvod — FundBlick okuplja ponude različitih trgovaca i prikazuje ukupnu cijenu s dostavom.',popular:'Isprobaj:',voiceStart:'Pokreni glasovno pretraživanje',voiceStop:'Zaustavi glasovno pretraživanje',listening:'Slušam …',voiceError:'Glasovno pretraživanje nije dostupno. Upiši pretragu.'},
    el:{search:'Αναζήτηση προϊόντος, μάρκας ή μοντέλου …',button:'Αναζήτηση',eyebrow:'ΑΝΑΖΗΤΗΣΗ ΠΡΟΪΟΝΤΩΝ · ΤΙΜΕΣ ΕΜΠΟΡΩΝ',hero:'Αναζήτησε. Σύγκρινε προσφορές. Έτοιμο.',lead:'Πληκτρολόγησε ένα προϊόν — το FundBlick συγκεντρώνει προσφορές από διαφορετικούς εμπόρους και δείχνει τη συνολική τιμή με τα μεταφορικά.',popular:'Δοκίμασε:',voiceStart:'Έναρξη φωνητικής αναζήτησης',voiceStop:'Διακοπή φωνητικής αναζήτησης',listening:'Ακούω …',voiceError:'Η φωνητική αναζήτηση δεν είναι διαθέσιμη. Πληκτρολόγησε την αναζήτησή σου.'},
    sr:{search:'Тражи производ, бренд или модел …',button:'Тражи',eyebrow:'ПРЕТРАГА ПРОИЗВОДА · ЦЕНЕ ПРОДАВАЦА',hero:'Тражи. Упореди понуде. Готово.',lead:'Унеси производ — FundBlick обједињује понуде различитих продаваца и приказује укупну цену са доставом.',popular:'Пробај:',voiceStart:'Покрени гласовну претрагу',voiceStop:'Заустави гласовну претрагу',listening:'Слушам …',voiceError:'Гласовна претрага није доступна. Унеси претрагу.'},
    es:{search:'Buscar producto, marca o modelo …',button:'Buscar',eyebrow:'BÚSQUEDA DE PRODUCTOS · PRECIOS DE COMERCIOS',hero:'Busca. Compara ofertas. Listo.',lead:'Introduce un producto — FundBlick reúne ofertas de distintos comercios y muestra el precio total con envío.',popular:'Prueba:',voiceStart:'Iniciar búsqueda por voz',voiceStop:'Detener búsqueda por voz',listening:'Escuchando …',voiceError:'La búsqueda por voz no está disponible. Escribe tu búsqueda.'},
    fr:{search:'Rechercher un produit, une marque ou un modèle …',button:'Rechercher',eyebrow:'RECHERCHE PRODUITS · PRIX DES MARCHANDS',hero:'Rechercher. Comparer les offres. Terminé.',lead:'Saisissez un produit — FundBlick regroupe les offres de différents marchands et affiche le prix total, livraison comprise.',popular:'Essayez:',voiceStart:'Démarrer la recherche vocale',voiceStop:'Arrêter la recherche vocale',listening:'Je vous écoute …',voiceError:'La recherche vocale est indisponible. Saisissez votre recherche.'},
    pt:{search:'Pesquisar produto, marca ou modelo …',button:'Pesquisar',eyebrow:'PESQUISA DE PRODUTOS · PREÇOS DE LOJAS',hero:'Pesquisa. Compara ofertas. Feito.',lead:'Introduz um produto — o FundBlick reúne ofertas de diferentes lojas e mostra o preço total com envio.',popular:'Experimenta:',voiceStart:'Iniciar pesquisa por voz',voiceStop:'Parar pesquisa por voz',listening:'A ouvir …',voiceError:'A pesquisa por voz não está disponível. Escreve a tua pesquisa.'},
    fa:{search:'جستجوی محصول، برند یا مدل …',button:'جستجو',eyebrow:'جستجوی محصول · قیمت فروشندگان',hero:'جستجو کن. پیشنهادها را مقایسه کن. تمام.',lead:'محصول را وارد کنید — FundBlick پیشنهادهای فروشندگان مختلف را جمع می‌کند و قیمت نهایی همراه با ارسال را نشان می‌دهد.',popular:'امتحان کنید:',voiceStart:'شروع جستجوی صوتی',voiceStop:'توقف جستجوی صوتی',listening:'گوش می‌دهم …',voiceError:'جستجوی صوتی در دسترس نیست. عبارت جستجو را تایپ کنید.'},
    sq:{search:'Kërko produkt, markë ose model …',button:'Kërko',eyebrow:'KËRKIM PRODUKTESH · ÇMIME SHITËSISH',hero:'Kërko. Krahaso ofertat. Gati.',lead:'Shkruaj produktin — FundBlick bashkon ofertat e shitësve të ndryshëm dhe tregon çmimin total me transport.',popular:'Provo:',voiceStart:'Fillo kërkimin me zë',voiceStop:'Ndalo kërkimin me zë',listening:'Po dëgjoj …',voiceError:'Kërkimi me zë nuk është i disponueshëm. Shkruaj kërkimin.'},
    'zh-Hans':{search:'搜索商品、品牌或型号 …',button:'搜索',eyebrow:'商品搜索 · 商家价格',hero:'搜索。比较报价。完成。',lead:'输入商品 — FundBlick 汇总不同商家的报价，并显示包含运费的总价。',popular:'试试：',voiceStart:'开始语音搜索',voiceStop:'停止语音搜索',listening:'正在聆听 …',voiceError:'语音搜索不可用。请手动输入搜索内容。'},
    ku:{search:'Hilber, marka an modelê bigere …',button:'Bigere',eyebrow:'LÊGERÎNA HILBERAN · BIHAYÊN FIROŞKARAN',hero:'Bigere. Pêşniyaran berawird bike. Qediya.',lead:'Hilberê binivîse — FundBlick pêşniyarên firoşkarên cuda berhev dike û bihayê giştî bi barkirinê re nîşan dide.',popular:'Biceribîne:',voiceStart:'Lêgerîna dengî dest pê bike',voiceStop:'Lêgerîna dengî rawestîne',listening:'Ez guhdar dikim …',voiceError:'Lêgerîna dengî ne berdest e. Lêgerîna xwe binivîse.'}
  };
  window.FUNDBLICK_LOCALES=Object.freeze(locales);
  window.FUNDBLICK_I18N=Object.freeze(copy);
})();
